package com.healthcare.storage.service;

import java.net.URI;
import java.time.Instant;
import java.util.UUID;

/**
 * Private object-storage boundary used by the consultation workflow.
 *
 * <p>The consultation domain owns the attachment row and its participant
 * authorization.  This boundary owns object-key generation, presigning and
 * the byte-level completion/scan checks.  Callers must persist the returned
 * key and scan result; a browser-supplied object key or {@code clean} flag is
 * never authoritative.</p>
 */
public interface ConsultationAttachmentStorage {

    /** Creates a short-lived, server-generated direct-upload URL. */
    UploadIntent createUploadIntent(UploadIntentRequest request);

    /** HEAD-only upload acknowledgment. Never downloads bytes or calls AV. */
    boolean isUploadPresent(CompletionRequest request);

    /**
     * HEADs and reads the uploaded object, verifies bytes, runs the scanner,
     * and promotes CLEAN bytes to a fresh server-only verified key.
     */
    CompletionResult complete(CompletionRequest request);

    /** Worker-only scan under a database lease; persistence must fence that lease. */
    CompletionResult scanWithLease(CompletionRequest request, AttachmentScanAuditHook.ScanLease lease);

    /**
     * Creates a short-lived GET URL only for an attachment already marked
     * CLEAN whose persisted key has the verified/download purpose.
     */
    DownloadUrl issueDownloadUrl(DownloadRequest request);

    /** Whether this boundary is enabled for the current runtime. */
    boolean isEnabled();

    enum Availability {
        ENABLED,
        DISABLED
    }

    enum ScanStatus {
        PENDING,
        CLEAN,
        REJECTED
    }

    /**
     * The client key is retained only for audit/debug correlation and is never
     * used as an object-store key.
     */
    record UploadIntentRequest(
            UUID threadId,
            UUID messageId,
            String requestedMimeType,
            long declaredSizeBytes,
            String declaredSha256,
            String clientObjectKey) {
    }

    /**
     * {@code attachmentId} and {@code privateObjectKey} are generated by the
     * server.  A disabled result has both URLs and the key set to {@code null}.
     */
    record UploadIntent(
            Availability availability,
            UUID attachmentId,
            String privateObjectKey,
            URI signedPutUrl,
            Instant putUrlExpiresAt,
            String status,
            String failureCode) {

        public static UploadIntent disabled(String failureCode) {
            return new UploadIntent(
                    Availability.DISABLED, null, null, null, null, "DISABLED", failureCode);
        }
    }

    record CompletionRequest(
            UUID threadId,
            UUID attachmentId,
            String privateObjectKey,
            String expectedMimeType,
            long expectedSizeBytes,
            String expectedSha256) {
    }

    record CompletionResult(
            Availability availability,
            UUID attachmentId,
            String privateObjectKey,
            String actualMimeType,
            long actualSizeBytes,
            String actualSha256,
            ScanStatus scanStatus,
            Instant completedAt,
            String failureCode) {

        /**
         * For CLEAN results {@code privateObjectKey} is the new immutable
         * verified key, never the mutable direct-upload key.
         */

        public static CompletionResult disabled(UUID attachmentId, String objectKey, String failureCode) {
            return new CompletionResult(
                    Availability.DISABLED,
                    attachmentId,
                    objectKey,
                    null,
                    0,
                    null,
                    ScanStatus.PENDING,
                    null,
                    failureCode);
        }

        public static CompletionResult rejected(
                UUID attachmentId,
                String objectKey,
                String actualMimeType,
                long actualSizeBytes,
                String actualSha256,
                String failureCode) {
            return new CompletionResult(
                    Availability.ENABLED,
                    attachmentId,
                    objectKey,
                    actualMimeType,
                    actualSizeBytes,
                    actualSha256,
                    ScanStatus.REJECTED,
                    Instant.now(),
                    failureCode);
        }

        public static CompletionResult pending(
                UUID attachmentId, String objectKey, String failureCode) {
            return new CompletionResult(
                    Availability.ENABLED,
                    attachmentId,
                    objectKey,
                    null,
                    0,
                    null,
                    ScanStatus.PENDING,
                    Instant.now(),
                    failureCode);
        }
    }

    record DownloadRequest(
            UUID threadId,
            UUID attachmentId,
            String privateObjectKey,
            ScanStatus persistedScanStatus,
            Long expectedSizeBytes) {
    }

    record DownloadUrl(
            Availability availability,
            UUID attachmentId,
            URI signedGetUrl,
            Instant getUrlExpiresAt,
            String failureCode) {

        public static DownloadUrl disabled(UUID attachmentId, String failureCode) {
            return new DownloadUrl(Availability.DISABLED, attachmentId, null, null, failureCode);
        }
    }
}
