-- Test fixture: catalog rows that migrations V86/V87 reference by fixed UUID.
--
-- Generated by scripts/generate-v86-fixture.py -- do not edit by hand.
--
-- V86 seeds appointments whose branch_id/doctor_id/package_id must already
-- exist; V87 adds more of the same. Production supplies those rows through the
-- admin CMS at runtime, and the migration chain on an EMPTY database was never
-- exercised, so the integration suite could not boot. CatalogFixtureCallback
-- executes this fixture immediately before V86; it is idempotent and a no-op
-- once the rows exist.
--
-- Row values are production-identical public catalog data.


INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '7765688c-354a-229a-6704-e4e460ccf3fa', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 4', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-4' AND id <> '7765688c-354a-229a-6704-e4e460ccf3fa') THEN 'cs-4-imp' ELSE 'cs-4' END, '4 Đường số 5, Quận 5, TP. Hồ Chí Minh', '028 38000004', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '40fabad4-9bac-c3e0-9d20-43fdf9168eb5', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 17', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-17' AND id <> '40fabad4-9bac-c3e0-9d20-43fdf9168eb5') THEN 'cs-17-imp' ELSE 'cs-17' END, '17 Đường số 18, Quận 6, TP. Hồ Chí Minh', '028 38000017', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '40fabad4-9bac-c3e0-9d20-43fdf9168eb5');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '8c310c68-033f-55d4-19e3-d63ed466d120', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 5', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-5' AND id <> '8c310c68-033f-55d4-19e3-d63ed466d120') THEN 'cs-5-imp' ELSE 'cs-5' END, '5 Đường số 6, Quận 6, TP. Hồ Chí Minh', '028 38000005', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '8c310c68-033f-55d4-19e3-d63ed466d120');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 20', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-20' AND id <> '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8') THEN 'cs-20-imp' ELSE 'cs-20' END, '20 Đường số 21, Quận 9, TP. Hồ Chí Minh', '028 38000020', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '7188f796-3d10-ca33-3d04-bfc7dab3932c', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 2', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-2' AND id <> '7188f796-3d10-ca33-3d04-bfc7dab3932c') THEN 'cs-2-imp' ELSE 'cs-2' END, '2 Đường số 3, Quận 3, TP. Hồ Chí Minh', '028 38000002', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT 'c2fee201-d898-4f79-cf65-113f9af836c9', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 15', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-15' AND id <> 'c2fee201-d898-4f79-cf65-113f9af836c9') THEN 'cs-15-imp' ELSE 'cs-15' END, '15 Đường số 16, Quận 4, TP. Hồ Chí Minh', '028 38000015', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = 'c2fee201-d898-4f79-cf65-113f9af836c9');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '535f4437-1f68-4926-14c8-2e9d29a4f684', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 3', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-3' AND id <> '535f4437-1f68-4926-14c8-2e9d29a4f684') THEN 'cs-3-imp' ELSE 'cs-3' END, '3 Đường số 4, Quận 4, TP. Hồ Chí Minh', '028 38000003', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '535f4437-1f68-4926-14c8-2e9d29a4f684');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 19', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-19' AND id <> 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7') THEN 'cs-19-imp' ELSE 'cs-19' END, '19 Đường số 20, Quận 8, TP. Hồ Chí Minh', '028 38000019', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT 'b8d0e0d9-6701-06bd-4eca-82216e9bd729', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 7', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-7' AND id <> 'b8d0e0d9-6701-06bd-4eca-82216e9bd729') THEN 'cs-7-imp' ELSE 'cs-7' END, '7 Đường số 8, Quận 8, TP. Hồ Chí Minh', '028 38000007', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = 'b8d0e0d9-6701-06bd-4eca-82216e9bd729');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '890d18bd-1881-12e9-ff66-a5bd8a8dc5d0', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 11', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-11' AND id <> '890d18bd-1881-12e9-ff66-a5bd8a8dc5d0') THEN 'cs-11-imp' ELSE 'cs-11' END, '11 Đường số 12, Quận 12, TP. Hồ Chí Minh', '028 38000011', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '890d18bd-1881-12e9-ff66-a5bd8a8dc5d0');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT 'f2738a9b-b915-9f55-8060-c825d70bfd1e', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 16', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-16' AND id <> 'f2738a9b-b915-9f55-8060-c825d70bfd1e') THEN 'cs-16-imp' ELSE 'cs-16' END, '16 Đường số 17, Quận 5, TP. Hồ Chí Minh', '028 38000016', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = 'f2738a9b-b915-9f55-8060-c825d70bfd1e');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT 'd2f61476-c56c-a8d9-ac80-0a1638ab1033', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 9', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-9' AND id <> 'd2f61476-c56c-a8d9-ac80-0a1638ab1033') THEN 'cs-9-imp' ELSE 'cs-9' END, '9 Đường số 10, Quận 10, TP. Hồ Chí Minh', '028 38000009', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = 'd2f61476-c56c-a8d9-ac80-0a1638ab1033');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 18', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-18' AND id <> '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689') THEN 'cs-18-imp' ELSE 'cs-18' END, '18 Đường số 19, Quận 7, TP. Hồ Chí Minh', '028 38000018', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '73309ada-e187-201f-1ba5-fb7b2a0ec7a1', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 8', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-8' AND id <> '73309ada-e187-201f-1ba5-fb7b2a0ec7a1') THEN 'cs-8-imp' ELSE 'cs-8' END, '8 Đường số 9, Quận 9, TP. Hồ Chí Minh', '028 38000008', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '566e252d-b253-e515-5969-467b3d3a2b77', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 12', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-12' AND id <> '566e252d-b253-e515-5969-467b3d3a2b77') THEN 'cs-12-imp' ELSE 'cs-12' END, '12 Đường số 13, Quận 1, TP. Hồ Chí Minh', '028 38000012', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '566e252d-b253-e515-5969-467b3d3a2b77');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '83d56555-dc7c-f749-7271-04e0d1843da1', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 13', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-13' AND id <> '83d56555-dc7c-f749-7271-04e0d1843da1') THEN 'cs-13-imp' ELSE 'cs-13' END, '13 Đường số 14, Quận 2, TP. Hồ Chí Minh', '028 38000013', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '83d56555-dc7c-f749-7271-04e0d1843da1');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT '7e0b9ff7-9df7-8e06-fd86-f4456c9a35d2', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 10', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-10' AND id <> '7e0b9ff7-9df7-8e06-fd86-f4456c9a35d2') THEN 'cs-10-imp' ELSE 'cs-10' END, '10 Đường số 11, Quận 11, TP. Hồ Chí Minh', '028 38000010', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '7e0b9ff7-9df7-8e06-fd86-f4456c9a35d2');
INSERT INTO branches (id, name, slug, address, phone, working_hours, active)
SELECT 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed', 'Bệnh viện Đa khoa Quốc tế HealthCare - Cơ sở 6', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = 'cs-6' AND id <> 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed') THEN 'cs-6-imp' ELSE 'cs-6' END, '6 Đường số 7, Quận 7, TP. Hồ Chí Minh', '028 38000006', '06:30–20:00, tất cả các ngày', true
WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');

-- Local-dev repair v2: prod-identical specialties referenced by V86/V87

INSERT INTO specialties (id, name, slug, description, active)
SELECT 'f5ca7735-d556-148a-ed43-65ca94e41ae5', 'Chấn thương chỉnh hình', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'chan-thuong-chinh-hinh' AND id <> 'f5ca7735-d556-148a-ed43-65ca94e41ae5') THEN 'chan-thuong-chinh-hinh-imp' ELSE 'chan-thuong-chinh-hinh' END, 'Điều trị gãy xương, trật khớp, chấn thương.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'f5ca7735-d556-148a-ed43-65ca94e41ae5');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '9cb56149-95dd-a351-ca75-b9b2f559d83b', 'Tiết niệu', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'tiet-nieu' AND id <> '9cb56149-95dd-a351-ca75-b9b2f559d83b') THEN 'tiet-nieu-imp' ELSE 'tiet-nieu' END, 'Điều trị bệnh lý thận, tiết niệu, nam khoa.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '9cb56149-95dd-a351-ca75-b9b2f559d83b');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'd898a94d-f778-a09e-a99c-060ebbbfd35e', 'Tai mũi họng', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'tai-mui-hong' AND id <> 'd898a94d-f778-a09e-a99c-060ebbbfd35e') THEN 'tai-mui-hong-imp' ELSE 'tai-mui-hong' END, 'Điều trị viêm họng, viêm xoang, rối loạn tiền đình.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'd898a94d-f778-a09e-a99c-060ebbbfd35e');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '7f80619b-9ece-f8d3-add2-12c4e6de963d', 'Mắt', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'mat' AND id <> '7f80619b-9ece-f8d3-add2-12c4e6de963d') THEN 'mat-imp' ELSE 'mat' END, 'Khám và điều trị bệnh lý mắt, đo kính.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '7f80619b-9ece-f8d3-add2-12c4e6de963d');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'd45a7cb5-269a-f76f-0554-ad3da3906c51', 'Nội tiết', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'noi-tiet' AND id <> 'd45a7cb5-269a-f76f-0554-ad3da3906c51') THEN 'noi-tiet-imp' ELSE 'noi-tiet' END, 'Điều trị tiểu đường, tuyến giáp, rối loạn chuyển hóa.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'd45a7cb5-269a-f76f-0554-ad3da3906c51');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '131199e1-749b-4a18-0c68-9605d41cb0a6', 'Thính học', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'thinh-hoc' AND id <> '131199e1-749b-4a18-0c68-9605d41cb0a6') THEN 'thinh-hoc-imp' ELSE 'thinh-hoc' END, 'Đánh giá thính lực, rối loạn thính giác.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '131199e1-749b-4a18-0c68-9605d41cb0a6');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'a9a176a3-00b5-0ed1-fb77-af6b1d7bd8d2', 'Cơ xương khớp', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'co-xuong-khop' AND id <> 'a9a176a3-00b5-0ed1-fb77-af6b1d7bd8d2') THEN 'co-xuong-khop-imp' ELSE 'co-xuong-khop' END, 'Điều trị đau khớp, thoái hóa cột sống, loãng xương.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'a9a176a3-00b5-0ed1-fb77-af6b1d7bd8d2');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '63263a8f-985d-56bd-4a91-cbc635681fb3', 'Ngoại khoa', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'ngoai-khoa' AND id <> '63263a8f-985d-56bd-4a91-cbc635681fb3') THEN 'ngoai-khoa-imp' ELSE 'ngoai-khoa' END, 'Phẫu thuật và can thiệp ngoại khoa tổng quát.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '63263a8f-985d-56bd-4a91-cbc635681fb3');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'ad181ca3-d18b-0da9-3d51-23b6150ae1aa', 'Da liễu thẩm mỹ', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'da-lieu-tham-my' AND id <> 'ad181ca3-d18b-0da9-3d51-23b6150ae1aa') THEN 'da-lieu-tham-my-imp' ELSE 'da-lieu-tham-my' END, 'Thẩm mỹ da, laser, điều trị sẹo.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'ad181ca3-d18b-0da9-3d51-23b6150ae1aa');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '82eecc5d-313f-8691-08f2-8adf830d567a', 'Hô hấp', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'ho-hap' AND id <> '82eecc5d-313f-8691-08f2-8adf830d567a') THEN 'ho-hap-imp' ELSE 'ho-hap' END, 'Khám và điều trị phổi, khí quản, dị ứng đường hô hấp.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '82eecc5d-313f-8691-08f2-8adf830d567a');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'd7851b0f-8adf-f780-b818-eb7670ec1e92', 'Huyết học', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'huyet-hoc' AND id <> 'd7851b0f-8adf-f780-b818-eb7670ec1e92') THEN 'huyet-hoc-imp' ELSE 'huyet-hoc' END, 'Điều trị bệnh lý máu, thiếu máu, rối loạn đông máu.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'd7851b0f-8adf-f780-b818-eb7670ec1e92');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '68c49671-774e-a89c-c9c1-b67a88de6bff', 'Giải phẫu bệnh', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'giai-phau-benh' AND id <> '68c49671-774e-a89c-c9c1-b67a88de6bff') THEN 'giai-phau-benh-imp' ELSE 'giai-phau-benh' END, 'Chẩn đoán bệnh lý mô, xét nghiệm giải phẫu.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '68c49671-774e-a89c-c9c1-b67a88de6bff');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '7eb6b5c1-3f8d-48c9-c54e-e35be9524ebf', 'Tiêu hóa', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'tieu-hoa' AND id <> '7eb6b5c1-3f8d-48c9-c54e-e35be9524ebf') THEN 'tieu-hoa-imp' ELSE 'tieu-hoa' END, 'Khám và điều trị bệnh lý dạ dày, đại tràng, gan mật.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '7eb6b5c1-3f8d-48c9-c54e-e35be9524ebf');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '3cd99926-6c7d-dd5b-183f-882ae9a0e469', 'Thần kinh', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'than-kinh' AND id <> '3cd99926-6c7d-dd5b-183f-882ae9a0e469') THEN 'than-kinh-imp' ELSE 'than-kinh' END, 'Khám và điều trị đau đầu, rối loạn giấc ngủ, bệnh lý thần kinh.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '3cd99926-6c7d-dd5b-183f-882ae9a0e469');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '462aa421-a88f-7105-7022-163467a83c2e', 'Ngoại thần kinh', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'ngoai-than-kinh' AND id <> '462aa421-a88f-7105-7022-163467a83c2e') THEN 'ngoai-than-kinh-imp' ELSE 'ngoai-than-kinh' END, 'Phẫu thuật sọ não, cột sống, dây thần kinh.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '462aa421-a88f-7105-7022-163467a83c2e');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '1a0976d1-bede-f974-5422-b58a922f0183', 'Dinh dưỡng', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'dinh-duong' AND id <> '1a0976d1-bede-f974-5422-b58a922f0183') THEN 'dinh-duong-imp' ELSE 'dinh-duong' END, 'Tư vấn chế độ ăn, dinh dưỡng lâm sàng.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '1a0976d1-bede-f974-5422-b58a922f0183');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '6a20be4b-ef6d-4d2f-b25d-11c2772440fd', 'Sản phụ khoa', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'san-phu-khoa' AND id <> '6a20be4b-ef6d-4d2f-b25d-11c2772440fd') THEN 'san-phu-khoa-imp' ELSE 'san-phu-khoa' END, 'Khám thai, tầm soát ung thư phụ khoa, sinh sản.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '6a20be4b-ef6d-4d2f-b25d-11c2772440fd');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '1a969127-309d-a67b-6460-48a75535074d', 'Y học cổ truyền', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'y-hoc-co-truyen' AND id <> '1a969127-309d-a67b-6460-48a75535074d') THEN 'y-hoc-co-truyen-imp' ELSE 'y-hoc-co-truyen' END, 'Bồi bổ, châm cứu, điều trị thuốc nam.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '1a969127-309d-a67b-6460-48a75535074d');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'b3379f28-d281-e976-0690-a0238f3b2038', 'Y tế công cộng', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'y-te-cong-cong' AND id <> 'b3379f28-d281-e976-0690-a0238f3b2038') THEN 'y-te-cong-cong-imp' ELSE 'y-te-cong-cong' END, 'Phòng bệnh, tiêm chủng, sức khỏe cộng đồng.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'b3379f28-d281-e976-0690-a0238f3b2038');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '5c20abac-9079-f9db-2819-3cbf167603b5', 'Tim mạch', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'tim-mach' AND id <> '5c20abac-9079-f9db-2819-3cbf167603b5') THEN 'tim-mach-imp' ELSE 'tim-mach' END, 'Khám và điều trị bệnh lý tim, mạch máu, tăng huyết áp.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '5c20abac-9079-f9db-2819-3cbf167603b5');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'ed14e1ac-5fe8-7043-3f00-ed1262c5150b', 'Sơ cấp cứu', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'so-cap-cuu' AND id <> 'ed14e1ac-5fe8-7043-3f00-ed1262c5150b') THEN 'so-cap-cuu-imp' ELSE 'so-cap-cuu' END, 'Xử trí cấp cứu, hồi sức tích cực.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'ed14e1ac-5fe8-7043-3f00-ed1262c5150b');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '1f721cc1-8cfd-0d5e-0098-3bc9999b57b2', 'Da liễu', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'da-lieu' AND id <> '1f721cc1-8cfd-0d5e-0098-3bc9999b57b2') THEN 'da-lieu-imp' ELSE 'da-lieu' END, 'Điều trị bệnh lý da, tóc, móng và thẩm mỹ da.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '1f721cc1-8cfd-0d5e-0098-3bc9999b57b2');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'c9eb17b1-996b-ef18-1057-7f6c9a550da0', 'Nam khoa', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'nam-khoa' AND id <> 'c9eb17b1-996b-ef18-1057-7f6c9a550da0') THEN 'nam-khoa-imp' ELSE 'nam-khoa' END, 'Khám và điều trị bệnh lý nam giới.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'c9eb17b1-996b-ef18-1057-7f6c9a550da0');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '2eba03c7-5d06-d23a-e7cb-4f74926ff849', 'Phục hồi chức năng', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'phuc-hoi-chuc-nang' AND id <> '2eba03c7-5d06-d23a-e7cb-4f74926ff849') THEN 'phuc-hoi-chuc-nang-imp' ELSE 'phuc-hoi-chuc-nang' END, 'Vật lý trị liệu, phục hồi sau bệnh.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '2eba03c7-5d06-d23a-e7cb-4f74926ff849');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '993e92ff-b71f-ae7c-090f-52572e5e3f11', 'Ung bướu', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'ung-buou' AND id <> '993e92ff-b71f-ae7c-090f-52572e5e3f11') THEN 'ung-buou-imp' ELSE 'ung-buou' END, 'Theo dõi và điều trị ung bướu, ung thư.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '993e92ff-b71f-ae7c-090f-52572e5e3f11');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'b47e0424-db07-65b2-d1f4-fc4e290ae4d6', 'Nhi khoa', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'nhi-khoa' AND id <> 'b47e0424-db07-65b2-d1f4-fc4e290ae4d6') THEN 'nhi-khoa-imp' ELSE 'nhi-khoa' END, 'Khám và điều trị bệnh lý trẻ em.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'b47e0424-db07-65b2-d1f4-fc4e290ae4d6');
INSERT INTO specialties (id, name, slug, description, active)
SELECT 'be4bd45f-857d-6836-c2e0-00bd6d6ad36c', 'Nội mạch máu', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'noi-mach-mau' AND id <> 'be4bd45f-857d-6836-c2e0-00bd6d6ad36c') THEN 'noi-mach-mau-imp' ELSE 'noi-mach-mau' END, 'Can thiệp mạch máu, siêu âm Doppler.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = 'be4bd45f-857d-6836-c2e0-00bd6d6ad36c');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '2065b16f-10a5-3781-439c-62dba14e4b52', 'Răng hàm mặt', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'rang-ham-mat' AND id <> '2065b16f-10a5-3781-439c-62dba14e4b52') THEN 'rang-ham-mat-imp' ELSE 'rang-ham-mat' END, 'Khám và điều trị răng, hàm, mặt.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '2065b16f-10a5-3781-439c-62dba14e4b52');
INSERT INTO specialties (id, name, slug, description, active)
SELECT '847f0834-7126-6c7d-bf07-610a46400a82', 'Nội tổng hợp', CASE WHEN EXISTS (SELECT 1 FROM specialties WHERE slug = 'noi-tong-hop' AND id <> '847f0834-7126-6c7d-bf07-610a46400a82') THEN 'noi-tong-hop-imp' ELSE 'noi-tong-hop' END, 'Khám sàng lọc, quản lý bệnh mãn tính.', true
WHERE NOT EXISTS (SELECT 1 FROM specialties WHERE id = '847f0834-7126-6c7d-bf07-610a46400a82');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc', 'BS.CKII Phạm Quốc Yến', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-333' AND id <> '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc') THEN 'bs-333-imp' ELSE 'bs-333' END, 'BS.CKII Phạm Quốc Yến có hơn 26 năm kinh nghiệm chuyên sâu trong lĩnh vực Cơ xương khớp. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc');

-- Local-dev repair v3: doctors referenced by V86/V87

INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '12c784f2-ab72-014c-d70d-1893f093a555', 'BS.CKII Nguyễn Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-75' AND id <> '12c784f2-ab72-014c-d70d-1893f093a555') THEN 'bs-75-imp' ELSE 'bs-75' END, 'BS.CKII Nguyễn Quốc Mai có hơn 11 năm kinh nghiệm chuyên sâu trong lĩnh vực Răng hàm mặt. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '12c784f2-ab72-014c-d70d-1893f093a555');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0fc63528-3464-37b2-8521-55b4869cd6ee', 'ThS.BS Nguyễn Quốc Trung', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-25' AND id <> '0fc63528-3464-37b2-8521-55b4869cd6ee') THEN 'bs-25-imp' ELSE 'bs-25' END, 'ThS.BS Nguyễn Quốc Trung có hơn 27 năm kinh nghiệm chuyên sâu trong lĩnh vực Nội tiết. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0fc63528-3464-37b2-8521-55b4869cd6ee');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0f1a8cb6-707d-03a0-1acb-83d8c61e2cb9', 'PGS.TS.BS Trần Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-471' AND id <> '0f1a8cb6-707d-03a0-1acb-83d8c61e2cb9') THEN 'bs-471-imp' ELSE 'bs-471' END, 'PGS.TS.BS Trần Quốc Hà có hơn 24 năm kinh nghiệm chuyên sâu trong lĩnh vực Nhi khoa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0f1a8cb6-707d-03a0-1acb-83d8c61e2cb9');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0f0245c2-fd64-efb4-5561-83404f179a22', 'ThS.BS Phạm Văn Long', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-218' AND id <> '0f0245c2-fd64-efb4-5561-83404f179a22') THEN 'bs-218-imp' ELSE 'bs-218' END, 'ThS.BS Phạm Văn Long có hơn 22 năm kinh nghiệm chuyên sâu trong lĩnh vực Hô hấp. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0f0245c2-fd64-efb4-5561-83404f179a22');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '083646c4-c3fa-3013-da09-e13691801fc5', 'PGS.TS.BS Phạm Văn Đức', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-438' AND id <> '083646c4-c3fa-3013-da09-e13691801fc5') THEN 'bs-438-imp' ELSE 'bs-438' END, 'PGS.TS.BS Phạm Văn Đức có hơn 24 năm kinh nghiệm chuyên sâu trong lĩnh vực Sơ cấp cứu. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '083646c4-c3fa-3013-da09-e13691801fc5');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0603349d-dfde-11a2-1033-50c3aa512b02', 'BS.CKII Lê Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-347' AND id <> '0603349d-dfde-11a2-1033-50c3aa512b02') THEN 'bs-347-imp' ELSE 'bs-347' END, 'BS.CKII Lê Quốc Mai có hơn 21 năm kinh nghiệm chuyên sâu trong lĩnh vực Răng hàm mặt. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0603349d-dfde-11a2-1033-50c3aa512b02');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0f49100f-3940-a9a2-f9d9-792b4a265768', 'BS.CKI Lê Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-107' AND id <> '0f49100f-3940-a9a2-f9d9-792b4a265768') THEN 'bs-107-imp' ELSE 'bs-107' END, 'BS.CKI Lê Quốc Mai có hơn 25 năm kinh nghiệm chuyên sâu trong lĩnh vực Sản phụ khoa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0f49100f-3940-a9a2-f9d9-792b4a265768');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0bbcf01f-2a31-3bdc-fea2-662af666bf12', 'BS.CKI Lê Văn Huy', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-132' AND id <> '0bbcf01f-2a31-3bdc-fea2-662af666bf12') THEN 'bs-132-imp' ELSE 'bs-132' END, 'BS.CKI Lê Văn Huy có hơn 10 năm kinh nghiệm chuyên sâu trong lĩnh vực Nội tổng hợp. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0bbcf01f-2a31-3bdc-fea2-662af666bf12');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '014624fb-6e10-8a38-b903-dcd2b742a8b1', 'BS.CKII Nguyễn Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-415' AND id <> '014624fb-6e10-8a38-b903-dcd2b742a8b1') THEN 'bs-415-imp' ELSE 'bs-415' END, 'BS.CKII Nguyễn Quốc Hà có hơn 11 năm kinh nghiệm chuyên sâu trong lĩnh vực Tiêu hóa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '014624fb-6e10-8a38-b903-dcd2b742a8b1');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '036a57a7-f401-0a9e-d51b-c6b7f7f6b755', 'BS.CKI Trần Văn Khôi', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-16' AND id <> '036a57a7-f401-0a9e-d51b-c6b7f7f6b755') THEN 'bs-16-imp' ELSE 'bs-16' END, 'BS.CKI Trần Văn Khôi có hơn 15 năm kinh nghiệm chuyên sâu trong lĩnh vực Sản phụ khoa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '036a57a7-f401-0a9e-d51b-c6b7f7f6b755');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '11720150-2ace-a89b-a007-105862080cc4', 'PGS.TS.BS Phạm Văn Huy', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-148' AND id <> '11720150-2ace-a89b-a007-105862080cc4') THEN 'bs-148-imp' ELSE 'bs-148' END, 'PGS.TS.BS Phạm Văn Huy có hơn 29 năm kinh nghiệm chuyên sâu trong lĩnh vực Tai mũi họng. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '11720150-2ace-a89b-a007-105862080cc4');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0e6cb13d-885f-c605-966a-13c0eaa951c1', 'BS.CKI Trần Quốc Yến', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-221' AND id <> '0e6cb13d-885f-c605-966a-13c0eaa951c1') THEN 'bs-221-imp' ELSE 'bs-221' END, 'BS.CKI Trần Quốc Yến có hơn 20 năm kinh nghiệm chuyên sâu trong lĩnh vực Tim mạch. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0e6cb13d-885f-c605-966a-13c0eaa951c1');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0350e3c4-3915-37e1-a2ad-59d5b2004f2a', 'PGS.TS.BS Võ Quốc Trung', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-89' AND id <> '0350e3c4-3915-37e1-a2ad-59d5b2004f2a') THEN 'bs-89-imp' ELSE 'bs-89' END, 'PGS.TS.BS Võ Quốc Trung có hơn 14 năm kinh nghiệm chuyên sâu trong lĩnh vực Nhi khoa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0350e3c4-3915-37e1-a2ad-59d5b2004f2a');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '00a2de74-0b8d-c45f-43f7-61f3d1f99612', 'BS.CKI Trần Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-111' AND id <> '00a2de74-0b8d-c45f-43f7-61f3d1f99612') THEN 'bs-111-imp' ELSE 'bs-111' END, 'BS.CKI Trần Quốc Hà có hơn 10 năm kinh nghiệm chuyên sâu trong lĩnh vực Tim mạch. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '00a2de74-0b8d-c45f-43f7-61f3d1f99612');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '11f7ef73-782f-7b86-7910-2e59c2e0bc5d', 'BS.CKI Võ Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-339' AND id <> '11f7ef73-782f-7b86-7910-2e59c2e0bc5d') THEN 'bs-339-imp' ELSE 'bs-339' END, 'BS.CKI Võ Quốc Mai có hơn 10 năm kinh nghiệm chuyên sâu trong lĩnh vực Mắt. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '11f7ef73-782f-7b86-7910-2e59c2e0bc5d');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0eba85fb-2c9d-c556-7aaf-6acfd33c8a95', 'BS.CKII Trần Quốc Trung', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-321' AND id <> '0eba85fb-2c9d-c556-7aaf-6acfd33c8a95') THEN 'bs-321-imp' ELSE 'bs-321' END, 'BS.CKII Trần Quốc Trung có hơn 21 năm kinh nghiệm chuyên sâu trong lĩnh vực Tiêu hóa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0eba85fb-2c9d-c556-7aaf-6acfd33c8a95');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '02b35c5e-c9f9-5cea-222c-b91d6e3dc4a4', 'TS.BS Nguyễn Văn Đức', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-190' AND id <> '02b35c5e-c9f9-5cea-222c-b91d6e3dc4a4') THEN 'bs-190-imp' ELSE 'bs-190' END, 'TS.BS Nguyễn Văn Đức có hơn 13 năm kinh nghiệm chuyên sâu trong lĩnh vực Thần kinh. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '02b35c5e-c9f9-5cea-222c-b91d6e3dc4a4');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '071d8e82-0c9e-6671-9dd8-196d1071f373', 'TS.BS Võ Văn Khôi', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-184' AND id <> '071d8e82-0c9e-6671-9dd8-196d1071f373') THEN 'bs-184-imp' ELSE 'bs-184' END, 'TS.BS Võ Văn Khôi có hơn 23 năm kinh nghiệm chuyên sâu trong lĩnh vực Dinh dưỡng. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '071d8e82-0c9e-6671-9dd8-196d1071f373');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '05866f27-98b4-7fd9-4e46-2f281ede4098', 'BS.CKI Phạm Quốc Trung', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-393' AND id <> '05866f27-98b4-7fd9-4e46-2f281ede4098') THEN 'bs-393-imp' ELSE 'bs-393' END, 'BS.CKI Phạm Quốc Trung có hơn 20 năm kinh nghiệm chuyên sâu trong lĩnh vực Mắt. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '05866f27-98b4-7fd9-4e46-2f281ede4098');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '096a389e-4cf8-5bff-ce07-1f1f1c988ba8', 'BS.CKI Lê Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-7' AND id <> '096a389e-4cf8-5bff-ce07-1f1f1c988ba8') THEN 'bs-7-imp' ELSE 'bs-7' END, 'BS.CKI Lê Quốc Hà có hơn 25 năm kinh nghiệm chuyên sâu trong lĩnh vực Nam khoa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '096a389e-4cf8-5bff-ce07-1f1f1c988ba8');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0155d6a0-5b06-f4a5-cc50-0e7fc94050ef', 'ThS.BS Lê Văn Huy', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-452' AND id <> '0155d6a0-5b06-f4a5-cc50-0e7fc94050ef') THEN 'bs-452-imp' ELSE 'bs-452' END, 'ThS.BS Lê Văn Huy có hơn 12 năm kinh nghiệm chuyên sâu trong lĩnh vực Hô hấp. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0155d6a0-5b06-f4a5-cc50-0e7fc94050ef');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0de3f854-5cbd-1e8e-3005-437d39c81cf2', 'BS.CKII Võ Văn Đức', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-454' AND id <> '0de3f854-5cbd-1e8e-3005-437d39c81cf2') THEN 'bs-454-imp' ELSE 'bs-454' END, 'BS.CKII Võ Văn Đức có hơn 16 năm kinh nghiệm chuyên sâu trong lĩnh vực Thính học. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0de3f854-5cbd-1e8e-3005-437d39c81cf2');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '06487368-ce38-e21c-36f9-3b0fa28de677', 'ThS.BS Lê Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-87' AND id <> '06487368-ce38-e21c-36f9-3b0fa28de677') THEN 'bs-87-imp' ELSE 'bs-87' END, 'ThS.BS Lê Quốc Hà có hơn 22 năm kinh nghiệm chuyên sâu trong lĩnh vực Ung bướu. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '06487368-ce38-e21c-36f9-3b0fa28de677');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b', 'BS.CKII Trần Văn Huy', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-156' AND id <> '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b') THEN 'bs-156-imp' ELSE 'bs-156' END, 'BS.CKII Trần Văn Huy có hơn 26 năm kinh nghiệm chuyên sâu trong lĩnh vực Y học cổ truyền. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc', 'BS.CKII Phạm Quốc Yến', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-333' AND id <> '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc') THEN 'bs-333-imp' ELSE 'bs-333' END, 'BS.CKII Phạm Quốc Yến có hơn 26 năm kinh nghiệm chuyên sâu trong lĩnh vực Cơ xương khớp. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0e333dc3-4388-6ae4-c059-f750302b16e0', 'ThS.BS Phạm Văn Huy', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-28' AND id <> '0e333dc3-4388-6ae4-c059-f750302b16e0') THEN 'bs-28-imp' ELSE 'bs-28' END, 'ThS.BS Phạm Văn Huy có hơn 17 năm kinh nghiệm chuyên sâu trong lĩnh vực Ngoại khoa. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0e333dc3-4388-6ae4-c059-f750302b16e0');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0467b23c-312e-25b9-af98-761fd1fffa9f', 'ThS.BS Lê Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-447' AND id <> '0467b23c-312e-25b9-af98-761fd1fffa9f') THEN 'bs-447-imp' ELSE 'bs-447' END, 'ThS.BS Lê Quốc Hà có hơn 17 năm kinh nghiệm chuyên sâu trong lĩnh vực Nội tiết. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0467b23c-312e-25b9-af98-761fd1fffa9f');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0bf4f049-ca5a-190c-78da-e9ed7434b87c', 'ThS.BS Phạm Văn Huy', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-228' AND id <> '0bf4f049-ca5a-190c-78da-e9ed7434b87c') THEN 'bs-228-imp' ELSE 'bs-228' END, 'ThS.BS Phạm Văn Huy có hơn 12 năm kinh nghiệm chuyên sâu trong lĩnh vực Chấn thương chỉnh hình. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0bf4f049-ca5a-190c-78da-e9ed7434b87c');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '101f11a4-62d5-4242-255b-04e57ce36978', 'TS.BS Lê Văn Đức', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-22' AND id <> '101f11a4-62d5-4242-255b-04e57ce36978') THEN 'bs-22-imp' ELSE 'bs-22' END, 'TS.BS Lê Văn Đức có hơn 28 năm kinh nghiệm chuyên sâu trong lĩnh vực Da liễu. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '101f11a4-62d5-4242-255b-04e57ce36978');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0be019cb-8f10-47d4-94f1-3fd82f1d8218', 'BS.CKII Nguyễn Văn Đức', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-230' AND id <> '0be019cb-8f10-47d4-94f1-3fd82f1d8218') THEN 'bs-230-imp' ELSE 'bs-230' END, 'BS.CKII Nguyễn Văn Đức có hơn 11 năm kinh nghiệm chuyên sâu trong lĩnh vực Y tế công cộng. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0be019cb-8f10-47d4-94f1-3fd82f1d8218');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '05152036-18cd-98a6-92a3-cfc64f6651dd', 'TS.BS Lê Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-467' AND id <> '05152036-18cd-98a6-92a3-cfc64f6651dd') THEN 'bs-467-imp' ELSE 'bs-467' END, 'TS.BS Lê Quốc Mai có hơn 18 năm kinh nghiệm chuyên sâu trong lĩnh vực Da liễu. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '05152036-18cd-98a6-92a3-cfc64f6651dd');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0a8552db-6c07-6e3c-3930-4ef03b19008c', 'TS.BS Trần Văn Long', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-346' AND id <> '0a8552db-6c07-6e3c-3930-4ef03b19008c') THEN 'bs-346-imp' ELSE 'bs-346' END, 'TS.BS Trần Văn Long có hơn 28 năm kinh nghiệm chuyên sâu trong lĩnh vực Huyết học. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0a8552db-6c07-6e3c-3930-4ef03b19008c');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0f0c7281-cb72-35ac-d7ba-e9106a543aea', 'TS.BS Lê Văn Đức', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-382' AND id <> '0f0c7281-cb72-35ac-d7ba-e9106a543aea') THEN 'bs-382-imp' ELSE 'bs-382' END, 'TS.BS Lê Văn Đức có hơn 23 năm kinh nghiệm chuyên sâu trong lĩnh vực Thần kinh. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0f0c7281-cb72-35ac-d7ba-e9106a543aea');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0d05ea81-c3a8-00bd-3c2b-1306065fafea', 'TS.BS Nguyễn Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-275' AND id <> '0d05ea81-c3a8-00bd-3c2b-1306065fafea') THEN 'bs-275-imp' ELSE 'bs-275' END, 'TS.BS Nguyễn Quốc Mai có hơn 13 năm kinh nghiệm chuyên sâu trong lĩnh vực Nội mạch máu. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0d05ea81-c3a8-00bd-3c2b-1306065fafea');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0e51eada-c05e-4d5f-25e5-73aea8120dd3', 'TS.BS Nguyễn Quốc Trung', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-305' AND id <> '0e51eada-c05e-4d5f-25e5-73aea8120dd3') THEN 'bs-305-imp' ELSE 'bs-305' END, 'TS.BS Nguyễn Quốc Trung có hơn 18 năm kinh nghiệm chuyên sâu trong lĩnh vực Ngoại thần kinh. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0e51eada-c05e-4d5f-25e5-73aea8120dd3');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0d84db0c-2936-5cbd-63d2-d808f1063a18', 'BS.CKI Võ Văn Long', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-74' AND id <> '0d84db0c-2936-5cbd-63d2-d808f1063a18') THEN 'bs-74-imp' ELSE 'bs-74' END, 'BS.CKI Võ Văn Long có hơn 15 năm kinh nghiệm chuyên sâu trong lĩnh vực Da liễu thẩm mỹ. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0d84db0c-2936-5cbd-63d2-d808f1063a18');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0a29aded-3774-021a-2b95-bb726ec11274', 'ThS.BS Nguyễn Quốc Hà', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-55' AND id <> '0a29aded-3774-021a-2b95-bb726ec11274') THEN 'bs-55-imp' ELSE 'bs-55' END, 'ThS.BS Nguyễn Quốc Hà có hơn 27 năm kinh nghiệm chuyên sâu trong lĩnh vực Phục hồi chức năng. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0a29aded-3774-021a-2b95-bb726ec11274');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0d712f3a-15a3-beaa-1ce0-9570257c1470', 'PGS.TS.BS Lê Quốc Yến', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-197' AND id <> '0d712f3a-15a3-beaa-1ce0-9570257c1470') THEN 'bs-197-imp' ELSE 'bs-197' END, 'PGS.TS.BS Lê Quốc Yến có hơn 14 năm kinh nghiệm chuyên sâu trong lĩnh vực Tiết niệu. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0d712f3a-15a3-beaa-1ce0-9570257c1470');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a', 'PGS.TS.BS Phạm Quốc Mai', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-243' AND id <> '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a') THEN 'bs-243-imp' ELSE 'bs-243' END, 'PGS.TS.BS Phạm Quốc Mai có hơn 19 năm kinh nghiệm chuyên sâu trong lĩnh vực Giải phẫu bệnh. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a');
INSERT INTO doctors (id, full_name, slug, bio, active)
SELECT '0585c0d7-3646-f502-d80a-0adcb2b184f1', 'PGS.TS.BS Trần Văn Khôi', CASE WHEN EXISTS (SELECT 1 FROM doctors WHERE slug = 'bs-296' AND id <> '0585c0d7-3646-f502-d80a-0adcb2b184f1') THEN 'bs-296-imp' ELSE 'bs-296' END, 'PGS.TS.BS Trần Văn Khôi có hơn 19 năm kinh nghiệm chuyên sâu trong lĩnh vực Tai mũi họng. Tốt nghiệp Bác sĩ Chuyên khoa tại Đại học Y Dược TP.HCM và tu nghiệp nâng cao tại các bệnh viện tuyến đầu, bác sĩ luôn cẩn trọng, tận tâm và đồng hành sát sao cùng người bệnh trong quá trình thăm khám, chẩn đoán và điều trị.', true
WHERE NOT EXISTS (SELECT 1 FROM doctors WHERE id = '0585c0d7-3646-f502-d80a-0adcb2b184f1');

INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:00a2de74-0b8d-c45f-43f7-61f3d1f99612:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '00a2de74-0b8d-c45f-43f7-61f3d1f99612', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '00a2de74-0b8d-c45f-43f7-61f3d1f99612' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:00a2de74-0b8d-c45f-43f7-61f3d1f99612:b8d0e0d9-6701-06bd-4eca-82216e9bd729')::uuid, '00a2de74-0b8d-c45f-43f7-61f3d1f99612', 'b8d0e0d9-6701-06bd-4eca-82216e9bd729'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '00a2de74-0b8d-c45f-43f7-61f3d1f99612' AND branch_id = 'b8d0e0d9-6701-06bd-4eca-82216e9bd729');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:014624fb-6e10-8a38-b903-dcd2b742a8b1:c3ec3c77-c1b5-0982-4e2f-06411fd165e7')::uuid, '014624fb-6e10-8a38-b903-dcd2b742a8b1', 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '014624fb-6e10-8a38-b903-dcd2b742a8b1' AND branch_id = 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0155d6a0-5b06-f4a5-cc50-0e7fc94050ef:c3ec3c77-c1b5-0982-4e2f-06411fd165e7')::uuid, '0155d6a0-5b06-f4a5-cc50-0e7fc94050ef', 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0155d6a0-5b06-f4a5-cc50-0e7fc94050ef' AND branch_id = 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:02b35c5e-c9f9-5cea-222c-b91d6e3dc4a4:83d56555-dc7c-f749-7271-04e0d1843da1')::uuid, '02b35c5e-c9f9-5cea-222c-b91d6e3dc4a4', '83d56555-dc7c-f749-7271-04e0d1843da1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '02b35c5e-c9f9-5cea-222c-b91d6e3dc4a4' AND branch_id = '83d56555-dc7c-f749-7271-04e0d1843da1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0350e3c4-3915-37e1-a2ad-59d5b2004f2a:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '0350e3c4-3915-37e1-a2ad-59d5b2004f2a', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0350e3c4-3915-37e1-a2ad-59d5b2004f2a' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:036a57a7-f401-0a9e-d51b-c6b7f7f6b755:535f4437-1f68-4926-14c8-2e9d29a4f684')::uuid, '036a57a7-f401-0a9e-d51b-c6b7f7f6b755', '535f4437-1f68-4926-14c8-2e9d29a4f684'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '036a57a7-f401-0a9e-d51b-c6b7f7f6b755' AND branch_id = '535f4437-1f68-4926-14c8-2e9d29a4f684');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:036a57a7-f401-0a9e-d51b-c6b7f7f6b755:c3ec3c77-c1b5-0982-4e2f-06411fd165e7')::uuid, '036a57a7-f401-0a9e-d51b-c6b7f7f6b755', 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '036a57a7-f401-0a9e-d51b-c6b7f7f6b755' AND branch_id = 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0467b23c-312e-25b9-af98-761fd1fffa9f:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '0467b23c-312e-25b9-af98-761fd1fffa9f', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0467b23c-312e-25b9-af98-761fd1fffa9f' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0467b23c-312e-25b9-af98-761fd1fffa9f:b8d0e0d9-6701-06bd-4eca-82216e9bd729')::uuid, '0467b23c-312e-25b9-af98-761fd1fffa9f', 'b8d0e0d9-6701-06bd-4eca-82216e9bd729'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0467b23c-312e-25b9-af98-761fd1fffa9f' AND branch_id = 'b8d0e0d9-6701-06bd-4eca-82216e9bd729');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:05152036-18cd-98a6-92a3-cfc64f6651dd:40fabad4-9bac-c3e0-9d20-43fdf9168eb5')::uuid, '05152036-18cd-98a6-92a3-cfc64f6651dd', '40fabad4-9bac-c3e0-9d20-43fdf9168eb5'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '05152036-18cd-98a6-92a3-cfc64f6651dd' AND branch_id = '40fabad4-9bac-c3e0-9d20-43fdf9168eb5');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:05152036-18cd-98a6-92a3-cfc64f6651dd:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '05152036-18cd-98a6-92a3-cfc64f6651dd', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '05152036-18cd-98a6-92a3-cfc64f6651dd' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0585c0d7-3646-f502-d80a-0adcb2b184f1:d2f61476-c56c-a8d9-ac80-0a1638ab1033')::uuid, '0585c0d7-3646-f502-d80a-0adcb2b184f1', 'd2f61476-c56c-a8d9-ac80-0a1638ab1033'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0585c0d7-3646-f502-d80a-0adcb2b184f1' AND branch_id = 'd2f61476-c56c-a8d9-ac80-0a1638ab1033');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:05866f27-98b4-7fd9-4e46-2f281ede4098:40fabad4-9bac-c3e0-9d20-43fdf9168eb5')::uuid, '05866f27-98b4-7fd9-4e46-2f281ede4098', '40fabad4-9bac-c3e0-9d20-43fdf9168eb5'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '05866f27-98b4-7fd9-4e46-2f281ede4098' AND branch_id = '40fabad4-9bac-c3e0-9d20-43fdf9168eb5');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:05866f27-98b4-7fd9-4e46-2f281ede4098:535f4437-1f68-4926-14c8-2e9d29a4f684')::uuid, '05866f27-98b4-7fd9-4e46-2f281ede4098', '535f4437-1f68-4926-14c8-2e9d29a4f684'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '05866f27-98b4-7fd9-4e46-2f281ede4098' AND branch_id = '535f4437-1f68-4926-14c8-2e9d29a4f684');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0603349d-dfde-11a2-1033-50c3aa512b02:85a7d1a5-ec91-61e1-fe4c-5231c723e7e8')::uuid, '0603349d-dfde-11a2-1033-50c3aa512b02', '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0603349d-dfde-11a2-1033-50c3aa512b02' AND branch_id = '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0603349d-dfde-11a2-1033-50c3aa512b02:c2fee201-d898-4f79-cf65-113f9af836c9')::uuid, '0603349d-dfde-11a2-1033-50c3aa512b02', 'c2fee201-d898-4f79-cf65-113f9af836c9'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0603349d-dfde-11a2-1033-50c3aa512b02' AND branch_id = 'c2fee201-d898-4f79-cf65-113f9af836c9');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:06487368-ce38-e21c-36f9-3b0fa28de677:890d18bd-1881-12e9-ff66-a5bd8a8dc5d0')::uuid, '06487368-ce38-e21c-36f9-3b0fa28de677', '890d18bd-1881-12e9-ff66-a5bd8a8dc5d0'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '06487368-ce38-e21c-36f9-3b0fa28de677' AND branch_id = '890d18bd-1881-12e9-ff66-a5bd8a8dc5d0');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:071d8e82-0c9e-6671-9dd8-196d1071f373:566e252d-b253-e515-5969-467b3d3a2b77')::uuid, '071d8e82-0c9e-6671-9dd8-196d1071f373', '566e252d-b253-e515-5969-467b3d3a2b77'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '071d8e82-0c9e-6671-9dd8-196d1071f373' AND branch_id = '566e252d-b253-e515-5969-467b3d3a2b77');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:071d8e82-0c9e-6671-9dd8-196d1071f373:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '071d8e82-0c9e-6671-9dd8-196d1071f373', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '071d8e82-0c9e-6671-9dd8-196d1071f373' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:083646c4-c3fa-3013-da09-e13691801fc5:7e0b9ff7-9df7-8e06-fd86-f4456c9a35d2')::uuid, '083646c4-c3fa-3013-da09-e13691801fc5', '7e0b9ff7-9df7-8e06-fd86-f4456c9a35d2'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '083646c4-c3fa-3013-da09-e13691801fc5' AND branch_id = '7e0b9ff7-9df7-8e06-fd86-f4456c9a35d2');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:083646c4-c3fa-3013-da09-e13691801fc5:c2fee201-d898-4f79-cf65-113f9af836c9')::uuid, '083646c4-c3fa-3013-da09-e13691801fc5', 'c2fee201-d898-4f79-cf65-113f9af836c9'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '083646c4-c3fa-3013-da09-e13691801fc5' AND branch_id = 'c2fee201-d898-4f79-cf65-113f9af836c9');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:096a389e-4cf8-5bff-ce07-1f1f1c988ba8:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '096a389e-4cf8-5bff-ce07-1f1f1c988ba8', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '096a389e-4cf8-5bff-ce07-1f1f1c988ba8' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:096a389e-4cf8-5bff-ce07-1f1f1c988ba8:c90115d2-40e8-79a1-75b9-dd233cd6d7ed')::uuid, '096a389e-4cf8-5bff-ce07-1f1f1c988ba8', 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '096a389e-4cf8-5bff-ce07-1f1f1c988ba8' AND branch_id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b:c90115d2-40e8-79a1-75b9-dd233cd6d7ed')::uuid, '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b', 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '09abbf2a-d771-8d5f-7ba2-4ab8dcfca55b' AND branch_id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0a29aded-3774-021a-2b95-bb726ec11274:c90115d2-40e8-79a1-75b9-dd233cd6d7ed')::uuid, '0a29aded-3774-021a-2b95-bb726ec11274', 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0a29aded-3774-021a-2b95-bb726ec11274' AND branch_id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0a8552db-6c07-6e3c-3930-4ef03b19008c:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '0a8552db-6c07-6e3c-3930-4ef03b19008c', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0a8552db-6c07-6e3c-3930-4ef03b19008c' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0bbcf01f-2a31-3bdc-fea2-662af666bf12:8c310c68-033f-55d4-19e3-d63ed466d120')::uuid, '0bbcf01f-2a31-3bdc-fea2-662af666bf12', '8c310c68-033f-55d4-19e3-d63ed466d120'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0bbcf01f-2a31-3bdc-fea2-662af666bf12' AND branch_id = '8c310c68-033f-55d4-19e3-d63ed466d120');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0be019cb-8f10-47d4-94f1-3fd82f1d8218:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '0be019cb-8f10-47d4-94f1-3fd82f1d8218', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0be019cb-8f10-47d4-94f1-3fd82f1d8218' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0be019cb-8f10-47d4-94f1-3fd82f1d8218:f2738a9b-b915-9f55-8060-c825d70bfd1e')::uuid, '0be019cb-8f10-47d4-94f1-3fd82f1d8218', 'f2738a9b-b915-9f55-8060-c825d70bfd1e'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0be019cb-8f10-47d4-94f1-3fd82f1d8218' AND branch_id = 'f2738a9b-b915-9f55-8060-c825d70bfd1e');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0bf4f049-ca5a-190c-78da-e9ed7434b87c:566e252d-b253-e515-5969-467b3d3a2b77')::uuid, '0bf4f049-ca5a-190c-78da-e9ed7434b87c', '566e252d-b253-e515-5969-467b3d3a2b77'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0bf4f049-ca5a-190c-78da-e9ed7434b87c' AND branch_id = '566e252d-b253-e515-5969-467b3d3a2b77');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0d05ea81-c3a8-00bd-3c2b-1306065fafea:d2f61476-c56c-a8d9-ac80-0a1638ab1033')::uuid, '0d05ea81-c3a8-00bd-3c2b-1306065fafea', 'd2f61476-c56c-a8d9-ac80-0a1638ab1033'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0d05ea81-c3a8-00bd-3c2b-1306065fafea' AND branch_id = 'd2f61476-c56c-a8d9-ac80-0a1638ab1033');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0d05ea81-c3a8-00bd-3c2b-1306065fafea:f2738a9b-b915-9f55-8060-c825d70bfd1e')::uuid, '0d05ea81-c3a8-00bd-3c2b-1306065fafea', 'f2738a9b-b915-9f55-8060-c825d70bfd1e'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0d05ea81-c3a8-00bd-3c2b-1306065fafea' AND branch_id = 'f2738a9b-b915-9f55-8060-c825d70bfd1e');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0d712f3a-15a3-beaa-1ce0-9570257c1470:83d56555-dc7c-f749-7271-04e0d1843da1')::uuid, '0d712f3a-15a3-beaa-1ce0-9570257c1470', '83d56555-dc7c-f749-7271-04e0d1843da1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0d712f3a-15a3-beaa-1ce0-9570257c1470' AND branch_id = '83d56555-dc7c-f749-7271-04e0d1843da1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0d712f3a-15a3-beaa-1ce0-9570257c1470:85a7d1a5-ec91-61e1-fe4c-5231c723e7e8')::uuid, '0d712f3a-15a3-beaa-1ce0-9570257c1470', '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0d712f3a-15a3-beaa-1ce0-9570257c1470' AND branch_id = '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0d84db0c-2936-5cbd-63d2-d808f1063a18:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '0d84db0c-2936-5cbd-63d2-d808f1063a18', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0d84db0c-2936-5cbd-63d2-d808f1063a18' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0d84db0c-2936-5cbd-63d2-d808f1063a18:c90115d2-40e8-79a1-75b9-dd233cd6d7ed')::uuid, '0d84db0c-2936-5cbd-63d2-d808f1063a18', 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0d84db0c-2936-5cbd-63d2-d808f1063a18' AND branch_id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0de3f854-5cbd-1e8e-3005-437d39c81cf2:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '0de3f854-5cbd-1e8e-3005-437d39c81cf2', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0de3f854-5cbd-1e8e-3005-437d39c81cf2' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0e333dc3-4388-6ae4-c059-f750302b16e0:6eb091fd-ba5b-86dc-d21d-7ba22e7c7689')::uuid, '0e333dc3-4388-6ae4-c059-f750302b16e0', '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0e333dc3-4388-6ae4-c059-f750302b16e0' AND branch_id = '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0e51eada-c05e-4d5f-25e5-73aea8120dd3:85a7d1a5-ec91-61e1-fe4c-5231c723e7e8')::uuid, '0e51eada-c05e-4d5f-25e5-73aea8120dd3', '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0e51eada-c05e-4d5f-25e5-73aea8120dd3' AND branch_id = '85a7d1a5-ec91-61e1-fe4c-5231c723e7e8');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0e5db434-b8fa-a4e8-23b8-2a6e35381b3a:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0e5db434-b8fa-a4e8-23b8-2a6e35381b3a:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0e5db434-b8fa-a4e8-23b8-2a6e35381b3a' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0e6cb13d-885f-c605-966a-13c0eaa951c1:c90115d2-40e8-79a1-75b9-dd233cd6d7ed')::uuid, '0e6cb13d-885f-c605-966a-13c0eaa951c1', 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0e6cb13d-885f-c605-966a-13c0eaa951c1' AND branch_id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0eba85fb-2c9d-c556-7aaf-6acfd33c8a95:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '0eba85fb-2c9d-c556-7aaf-6acfd33c8a95', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0eba85fb-2c9d-c556-7aaf-6acfd33c8a95' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f0245c2-fd64-efb4-5561-83404f179a22:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '0f0245c2-fd64-efb4-5561-83404f179a22', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f0245c2-fd64-efb4-5561-83404f179a22' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f0245c2-fd64-efb4-5561-83404f179a22:f2738a9b-b915-9f55-8060-c825d70bfd1e')::uuid, '0f0245c2-fd64-efb4-5561-83404f179a22', 'f2738a9b-b915-9f55-8060-c825d70bfd1e'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f0245c2-fd64-efb4-5561-83404f179a22' AND branch_id = 'f2738a9b-b915-9f55-8060-c825d70bfd1e');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f0c7281-cb72-35ac-d7ba-e9106a543aea:566e252d-b253-e515-5969-467b3d3a2b77')::uuid, '0f0c7281-cb72-35ac-d7ba-e9106a543aea', '566e252d-b253-e515-5969-467b3d3a2b77'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f0c7281-cb72-35ac-d7ba-e9106a543aea' AND branch_id = '566e252d-b253-e515-5969-467b3d3a2b77');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f0c7281-cb72-35ac-d7ba-e9106a543aea:c3ec3c77-c1b5-0982-4e2f-06411fd165e7')::uuid, '0f0c7281-cb72-35ac-d7ba-e9106a543aea', 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f0c7281-cb72-35ac-d7ba-e9106a543aea' AND branch_id = 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f1a8cb6-707d-03a0-1acb-83d8c61e2cb9:c3ec3c77-c1b5-0982-4e2f-06411fd165e7')::uuid, '0f1a8cb6-707d-03a0-1acb-83d8c61e2cb9', 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f1a8cb6-707d-03a0-1acb-83d8c61e2cb9' AND branch_id = 'c3ec3c77-c1b5-0982-4e2f-06411fd165e7');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f49100f-3940-a9a2-f9d9-792b4a265768:c90115d2-40e8-79a1-75b9-dd233cd6d7ed')::uuid, '0f49100f-3940-a9a2-f9d9-792b4a265768', 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f49100f-3940-a9a2-f9d9-792b4a265768' AND branch_id = 'c90115d2-40e8-79a1-75b9-dd233cd6d7ed');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc:6eb091fd-ba5b-86dc-d21d-7ba22e7c7689')::uuid, '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc', '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc' AND branch_id = '6eb091fd-ba5b-86dc-d21d-7ba22e7c7689');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0f7a70b6-dbc4-36e4-59b4-e1e98ecb36bc' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:0fc63528-3464-37b2-8521-55b4869cd6ee:f2738a9b-b915-9f55-8060-c825d70bfd1e')::uuid, '0fc63528-3464-37b2-8521-55b4869cd6ee', 'f2738a9b-b915-9f55-8060-c825d70bfd1e'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '0fc63528-3464-37b2-8521-55b4869cd6ee' AND branch_id = 'f2738a9b-b915-9f55-8060-c825d70bfd1e');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:101f11a4-62d5-4242-255b-04e57ce36978:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '101f11a4-62d5-4242-255b-04e57ce36978', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '101f11a4-62d5-4242-255b-04e57ce36978' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:101f11a4-62d5-4242-255b-04e57ce36978:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '101f11a4-62d5-4242-255b-04e57ce36978', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '101f11a4-62d5-4242-255b-04e57ce36978' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:11720150-2ace-a89b-a007-105862080cc4:73309ada-e187-201f-1ba5-fb7b2a0ec7a1')::uuid, '11720150-2ace-a89b-a007-105862080cc4', '73309ada-e187-201f-1ba5-fb7b2a0ec7a1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '11720150-2ace-a89b-a007-105862080cc4' AND branch_id = '73309ada-e187-201f-1ba5-fb7b2a0ec7a1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:11720150-2ace-a89b-a007-105862080cc4:83d56555-dc7c-f749-7271-04e0d1843da1')::uuid, '11720150-2ace-a89b-a007-105862080cc4', '83d56555-dc7c-f749-7271-04e0d1843da1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '11720150-2ace-a89b-a007-105862080cc4' AND branch_id = '83d56555-dc7c-f749-7271-04e0d1843da1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:11f7ef73-782f-7b86-7910-2e59c2e0bc5d:83d56555-dc7c-f749-7271-04e0d1843da1')::uuid, '11f7ef73-782f-7b86-7910-2e59c2e0bc5d', '83d56555-dc7c-f749-7271-04e0d1843da1'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '11f7ef73-782f-7b86-7910-2e59c2e0bc5d' AND branch_id = '83d56555-dc7c-f749-7271-04e0d1843da1');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:12c784f2-ab72-014c-d70d-1893f093a555:7188f796-3d10-ca33-3d04-bfc7dab3932c')::uuid, '12c784f2-ab72-014c-d70d-1893f093a555', '7188f796-3d10-ca33-3d04-bfc7dab3932c'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '12c784f2-ab72-014c-d70d-1893f093a555' AND branch_id = '7188f796-3d10-ca33-3d04-bfc7dab3932c');
INSERT INTO doctor_branches (id, doctor_id, branch_id)
SELECT md5('fixture:30000000-0000-0000-0000-000000000001:7765688c-354a-229a-6704-e4e460ccf3fa')::uuid, '30000000-0000-0000-0000-000000000001', '7765688c-354a-229a-6704-e4e460ccf3fa'
WHERE NOT EXISTS (SELECT 1 FROM doctor_branches
   WHERE doctor_id = '30000000-0000-0000-0000-000000000001' AND branch_id = '7765688c-354a-229a-6704-e4e460ccf3fa');

-- Local-dev / test repair: the CMS content rows that V86's audit-trail seed
-- references by fixed UUID. V86 seeds cms_content_changes rows for the
-- homepage and careers heroes, expecting the corresponding cms_contents rows
-- to exist; a production database created them through the admin CMS, and no
-- migration creates them, so a fresh database failed V86's FK. Payloads match
-- the public copy V86 publishes in the change rows, so a page that reads the
-- slot renders the same content either way.

INSERT INTO cms_contents (id, slot_key, component_type, payload, status, version, created_at, updated_at)
SELECT '80000000-0000-0000-0000-000000000001', 'homepage.hero', 'HERO',
       '{"eyebrow":"Chăm sóc chủ động","title":"Đồng hành cùng sức khỏe gia đình","body":"Đặt lịch khám và tìm hiểu dịch vụ chăm sóc phù hợp với nhu cầu của bạn.","ctaLabel":"Đặt lịch khám","ctaHref":"/dat-lich"}'::jsonb,
       'PUBLISHED', 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '10 days'
WHERE NOT EXISTS (SELECT 1 FROM cms_contents WHERE id = '80000000-0000-0000-0000-000000000001');

INSERT INTO cms_contents (id, slot_key, component_type, payload, status, version, created_at, updated_at)
SELECT '80000000-0000-0000-0000-000000000002', 'careers.hero', 'HERO',
       '{"eyebrow":"Cơ hội nghề nghiệp tại HealthCare","title":"Cùng chăm sóc người bệnh bằng năng lực và sự tử tế","body":"Khám phá môi trường làm việc đề cao an toàn, phối hợp liên chuyên môn và sự phát triển bền vững của mỗi thành viên.","ctaLabel":"Xem vị trí đang tuyển","ctaHref":"/careers#vi-tri-dang-tuyen"}'::jsonb,
       'PUBLISHED', 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '10 days'
WHERE NOT EXISTS (SELECT 1 FROM cms_contents WHERE id = '80000000-0000-0000-0000-000000000002');

INSERT INTO cms_contents (id, slot_key, component_type, payload, status, version, created_at, updated_at)
SELECT '80000000-0000-0000-0000-000000000003', 'careers.body', 'RICH_TEXT',
       '{"title":"Điều chúng tôi mong đợi ở đồng đội","body":"Chúng tôi trân trọng tinh thần học hỏi, giao tiếp rõ ràng và cam kết đặt an toàn của người bệnh lên hàng đầu trong mọi vai trò."}'::jsonb,
       'PUBLISHED', 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '10 days'
WHERE NOT EXISTS (SELECT 1 FROM cms_contents WHERE id = '80000000-0000-0000-0000-000000000003');

INSERT INTO cms_contents (id, slot_key, component_type, payload, status, version, created_at, updated_at)
SELECT '80000000-0000-0000-0000-000000000004', 'search.hero', 'HERO',
       '{"eyebrow":"Catalog active","title":"Tìm kiếm theo dữ liệu đã xuất bản","body":"Kết quả được lọc trực tiếp từ chuyên khoa, bác sĩ, dịch vụ, gói khám và cẩm nang của backend."}'::jsonb,
       'PUBLISHED', 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '10 days'
WHERE NOT EXISTS (SELECT 1 FROM cms_contents WHERE id = '80000000-0000-0000-0000-000000000004');

INSERT INTO cms_contents (id, slot_key, component_type, payload, status, version, created_at, updated_at)
SELECT '80000000-0000-0000-0000-000000000005', 'homepage.body', 'RICH_TEXT',
       '{"title":"Hành trình chăm sóc được cập nhật","body":"Thông tin mới từ quản trị viên sẽ xuất hiện tại đây theo version đã xuất bản. Dữ liệu chuyên khoa, bác sĩ và cơ sở vẫn được đọc trực tiếp từ catalog backend."}'::jsonb,
       'PUBLISHED', 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '10 days'
WHERE NOT EXISTS (SELECT 1 FROM cms_contents WHERE id = '80000000-0000-0000-0000-000000000005');

-- Local-dev repair: packages referenced by V87

INSERT INTO packages (id, name, slug, description, price, active)
SELECT 'eaa5b00f-0290-3672-945d-9ac715b07b3c', 'Gói kiểm tra Cơ xương khớp & Phòng chống Loãng xương (Hạng 6)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-6' AND id <> 'eaa5b00f-0290-3672-945d-9ac715b07b3c') THEN 'goi-6-imp' ELSE 'goi-6' END, 'Đo mật độ xương DEXA, xét nghiệm Calci ion, Acid Uric máu và chụp X-quang khớp gối hoặc cột sống thắt lưng.', 3200000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = 'eaa5b00f-0290-3672-945d-9ac715b07b3c');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '179579a2-744b-571e-7887-a371a50aa4f8', 'Gói kiểm tra Cơ xương khớp & Phòng chống Loãng xương (Hạng 3)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-32' AND id <> '179579a2-744b-571e-7887-a371a50aa4f8') THEN 'goi-32-imp' ELSE 'goi-32' END, 'Đo mật độ xương DEXA, xét nghiệm Calci ion, Acid Uric máu và chụp X-quang khớp gối hoặc cột sống thắt lưng.', 2600000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '179579a2-744b-571e-7887-a371a50aa4f8');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '16931bc9-6b86-3cc4-de8e-53670e99ce41', 'Gói khám sức khỏe tổng quát Định kỳ Chuẩn (Hạng 6)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-54' AND id <> '16931bc9-6b86-3cc4-de8e-53670e99ce41') THEN 'goi-54-imp' ELSE 'goi-54' END, 'Rà soát toàn diện 25 chỉ số sinh hóa, huyết học, X-quang phổi và siêu âm ổ bụng tổng quát cho người trưởng thành.', 2850000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '16931bc9-6b86-3cc4-de8e-53670e99ce41');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '7a70d6c6-82fb-e926-f76e-a824384abd12', 'Gói tầm soát Đột quỵ Não & Bệnh lý Mạch máu Chuyên sâu (Hạng 3)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-33' AND id <> '7a70d6c6-82fb-e926-f76e-a824384abd12') THEN 'goi-33-imp' ELSE 'goi-33' END, 'Chụp cộng hưởng từ sọ não và mạch máu não MRA 1.5 Tesla, siêu âm Doppler động mạch cảnh và điện tâm đồ.', 5200000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '7a70d6c6-82fb-e926-f76e-a824384abd12');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '81ffe666-2065-f436-5a81-eb44eb6333fc', 'Gói tầm soát Đột quỵ Não & Bệnh lý Mạch máu Chuyên sâu (Hạng 8)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-79' AND id <> '81ffe666-2065-f436-5a81-eb44eb6333fc') THEN 'goi-79-imp' ELSE 'goi-79' END, 'Chụp cộng hưởng từ sọ não và mạch máu não MRA 1.5 Tesla, siêu âm Doppler động mạch cảnh và điện tâm đồ.', 6200000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '81ffe666-2065-f436-5a81-eb44eb6333fc');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '946ce7df-65e3-1a39-68ee-043db4ca6b3f', 'Gói tầm soát Tim mạch và Huyết áp Nâng cao', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-10' AND id <> '946ce7df-65e3-1a39-68ee-043db4ca6b3f') THEN 'goi-10-imp' ELSE 'goi-10' END, 'Đánh giá nguy cơ xơ vữa động mạch, đo điện tâm đồ gắng sức, siêu âm tim Doppler và định lượng men tim chuyên sâu.', 3200000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '946ce7df-65e3-1a39-68ee-043db4ca6b3f');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '4c5024ec-29cb-e9d3-bce9-7805c9ef34fc', 'Gói tầm soát Đột quỵ Não & Bệnh lý Mạch máu Chuyên sâu (Hạng 7)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-7' AND id <> '4c5024ec-29cb-e9d3-bce9-7805c9ef34fc') THEN 'goi-7-imp' ELSE 'goi-7' END, 'Chụp cộng hưởng từ sọ não và mạch máu não MRA 1.5 Tesla, siêu âm Doppler động mạch cảnh và điện tâm đồ.', 6000000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '4c5024ec-29cb-e9d3-bce9-7805c9ef34fc');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT 'dbfb4e7f-da3d-57d3-3573-c26528482839', 'Gói khám Sức khỏe VIP Doanh nhân Toàn diện (Hạng 9)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-9' AND id <> 'dbfb4e7f-da3d-57d3-3573-c26528482839') THEN 'goi-9-imp' ELSE 'goi-9' END, 'Khám toàn bộ các chuyên khoa với Giáo sư/Tiến sĩ, chụp MRI não, nội soi tiêu hóa trọn gói và dịch vụ phòng chờ VIP.', 10500000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = 'dbfb4e7f-da3d-57d3-3573-c26528482839');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '77823225-a569-2ce2-b913-4c6d71adfac8', 'Gói chăm sóc Sức khỏe Phụ nữ Toàn diện', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-11' AND id <> '77823225-a569-2ce2-b913-4c6d71adfac8') THEN 'goi-11-imp' ELSE 'goi-11' END, 'Khám phụ khoa, siêu âm tuyến vú, siêu âm tử cung phần phụ và xét nghiệm sàng lọc tế bào cổ tử cung ThinPrep.', 2650000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '77823225-a569-2ce2-b913-4c6d71adfac8');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '44efce0e-6734-a401-7714-50c710221fe2', 'Gói khám Tiền hôn nhân cho Cặp đôi (Hạng 8)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-8' AND id <> '44efce0e-6734-a401-7714-50c710221fe2') THEN 'goi-8-imp' ELSE 'goi-8' END, 'Kiểm tra sức khỏe sinh sản, xét nghiệm bệnh truyền nhiễm, nhóm máu Rh và sàng lọc gen bệnh tan máu Thalassemia.', 5000000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '44efce0e-6734-a401-7714-50c710221fe2');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT 'a7fc3862-6ed1-b5f8-8803-02ddee4f6379', 'Gói tầm soát Đái tháo đường & Hội chứng Chuyển hóa (Hạng 8)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-77' AND id <> 'a7fc3862-6ed1-b5f8-8803-02ddee4f6379') THEN 'goi-77-imp' ELSE 'goi-77' END, 'Đo đường huyết lúc đói, HbA1c, bộ mỡ máu 4 thành phần, microalbumin niệu và soi đáy mắt phát hiện biến chứng sớm.', 3350000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = 'a7fc3862-6ed1-b5f8-8803-02ddee4f6379');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT 'f0f63287-50dd-36b4-b29d-07fbcf7a9f0a', 'Gói khám Tiền hôn nhân cho Cặp đôi (Hạng 3)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-34' AND id <> 'f0f63287-50dd-36b4-b29d-07fbcf7a9f0a') THEN 'goi-34-imp' ELSE 'goi-34' END, 'Kiểm tra sức khỏe sinh sản, xét nghiệm bệnh truyền nhiễm, nhóm máu Rh và sàng lọc gen bệnh tan máu Thalassemia.', 4000000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = 'f0f63287-50dd-36b4-b29d-07fbcf7a9f0a');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT 'a94904c5-e237-4f3e-fa94-fb3e030df87b', 'Gói kiểm tra Sức khỏe Trẻ em & Phát triển Thể chất', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-12' AND id <> 'a94904c5-e237-4f3e-fa94-fb3e030df87b') THEN 'goi-12-imp' ELSE 'goi-12' END, 'Đánh giá dinh dưỡng, vi chất, siêu âm bụng tổng quát, kiểm tra thị lực, tai mũi họng và tư vấn tiêm chủng cho bé.', 1450000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = 'a94904c5-e237-4f3e-fa94-fb3e030df87b');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '3bacd204-83af-68a6-9781-a12472ee71bf', 'Gói tầm soát Đái tháo đường & Hội chứng Chuyển hóa (Hạng 5)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-5' AND id <> '3bacd204-83af-68a6-9781-a12472ee71bf') THEN 'goi-5-imp' ELSE 'goi-5' END, 'Đo đường huyết lúc đói, HbA1c, bộ mỡ máu 4 thành phần, microalbumin niệu và soi đáy mắt phát hiện biến chứng sớm.', 2750000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '3bacd204-83af-68a6-9781-a12472ee71bf');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '097bdfc5-d514-1245-b3fe-72e04d871339', 'Gói tầm soát Đái tháo đường & Hội chứng Chuyển hóa (Hạng 3)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-31' AND id <> '097bdfc5-d514-1245-b3fe-72e04d871339') THEN 'goi-31-imp' ELSE 'goi-31' END, 'Đo đường huyết lúc đói, HbA1c, bộ mỡ máu 4 thành phần, microalbumin niệu và soi đáy mắt phát hiện biến chứng sớm.', 2350000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '097bdfc5-d514-1245-b3fe-72e04d871339');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '5d19a424-51c3-148f-b00a-14528aa09300', 'Gói khám Sức khỏe VIP Doanh nhân Toàn diện (Hạng 3)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-35' AND id <> '5d19a424-51c3-148f-b00a-14528aa09300') THEN 'goi-35-imp' ELSE 'goi-35' END, 'Khám toàn bộ các chuyên khoa với Giáo sư/Tiến sĩ, chụp MRI não, nội soi tiêu hóa trọn gói và dịch vụ phòng chờ VIP.', 9300000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '5d19a424-51c3-148f-b00a-14528aa09300');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '938260f7-85fb-43d2-b9f6-b14c46a39e16', 'Gói kiểm tra Sức khỏe Trẻ em & Phát triển Thể chất (Hạng 4)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-4' AND id <> '938260f7-85fb-43d2-b9f6-b14c46a39e16') THEN 'goi-4-imp' ELSE 'goi-4' END, 'Đánh giá dinh dưỡng, vi chất, siêu âm bụng tổng quát, kiểm tra thị lực, tai mũi họng và tư vấn tiêm chủng cho bé.', 2050000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '938260f7-85fb-43d2-b9f6-b14c46a39e16');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '8d47632e-e4d1-82a5-30f6-2d88fad7f176', 'Gói khám sức khỏe tổng quát Định kỳ Chuẩn (Hạng 4)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-36' AND id <> '8d47632e-e4d1-82a5-30f6-2d88fad7f176') THEN 'goi-36-imp' ELSE 'goi-36' END, 'Rà soát toàn diện 25 chỉ số sinh hóa, huyết học, X-quang phổi và siêu âm ổ bụng tổng quát cho người trưởng thành.', 2450000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '8d47632e-e4d1-82a5-30f6-2d88fad7f176');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT '3359a223-3b09-6aa1-7415-c6be16271649', 'Gói kiểm tra Cơ xương khớp & Phòng chống Loãng xương (Hạng 8)', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-78' AND id <> '3359a223-3b09-6aa1-7415-c6be16271649') THEN 'goi-78-imp' ELSE 'goi-78' END, 'Đo mật độ xương DEXA, xét nghiệm Calci ion, Acid Uric máu và chụp X-quang khớp gối hoặc cột sống thắt lưng.', 3600000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = '3359a223-3b09-6aa1-7415-c6be16271649');
INSERT INTO packages (id, name, slug, description, price, active)
SELECT 'ed23f337-3ee2-8c5b-51a7-a5fb511cd00b', 'Gói khám sức khỏe tổng quát Định kỳ Chuẩn', CASE WHEN EXISTS (SELECT 1 FROM packages WHERE slug='goi-1' AND id <> 'ed23f337-3ee2-8c5b-51a7-a5fb511cd00b') THEN 'goi-1-imp' ELSE 'goi-1' END, 'Rà soát toàn diện 25 chỉ số sinh hóa, huyết học, X-quang phổi và siêu âm ổ bụng tổng quát cho người trưởng thành.', 1850000.0, true
WHERE NOT EXISTS (SELECT 1 FROM packages WHERE id = 'ed23f337-3ee2-8c5b-51a7-a5fb511cd00b');


-- ---------------------------------------------------------------------------
-- Supplemental governance users (added after the generated catalog block).
--
-- V86 seeds health_question_answers authored by user ...023 and reviewed by
-- user ...0002. On a chain grown against a database that already claimed the
-- demo emails (or in an isolated migration schema), V58's ON CONFLICT (email)
-- upsert keeps a pre-existing id and those UUIDs never come into existence;
-- the health_question_answer_guard trigger then correctly rejects the seed
-- rows. These fixture users make the fresh-database chain match production's
-- governance state. Guarded, idempotent, fixture-only.
-- ---------------------------------------------------------------------------

INSERT INTO users (id, email, password_hash, display_name, status, email_verified, email_verified_at, created_at, updated_at)
SELECT '90000000-0000-0000-0000-000000000023', 'v86-fixture-doctor@healthcare.local', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ThS.BS Trần Thu Hà', 'ACTIVE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM users WHERE id = '90000000-0000-0000-0000-000000000023');

INSERT INTO user_roles (user_id, role_id)
SELECT '90000000-0000-0000-0000-000000000023', r.id FROM roles r WHERE r.code = 'DOCTOR'
ON CONFLICT DO NOTHING;

INSERT INTO users (id, email, password_hash, display_name, status, email_verified, email_verified_at, created_at, updated_at)
SELECT '90000000-0000-0000-0000-000000000002', 'v86-fixture-reviewer@healthcare.local', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'BS Nguyễn Quốc Trọng', 'ACTIVE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM users WHERE id = '90000000-0000-0000-0000-000000000002');

INSERT INTO user_roles (user_id, role_id)
SELECT '90000000-0000-0000-0000-000000000002', r.id FROM roles r WHERE r.code = 'DOCTOR'
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Public-schema visibility for the guard V86 re-pins inside its own script.
--
-- V86 executes `ALTER FUNCTION health_question_answer_guard() SET search_path =
-- public, extensions, pg_catalog` five statements before it seeds
-- health_question_answers, and never restores it. From that point on the guard
-- resolves users / roles / user_roles in PUBLIC even when the chain itself runs
-- in an isolated schema (FlywayMigrationTest). Production cannot hit this: there
-- the migration schema *is* public, and V56 (...0002 = doctor@healthcare.local)
-- and V58 (...023 = doctor@healthcare.com) already hold both authors as active
-- DOCTORs, which is exactly why the same chain succeeds on public.
--
-- align-guard-search-path.sql cannot repair it — that script runs before V86 and
-- V86 overrides it mid-migration. So the read target the guard ends up pinned
-- to has to carry the governance state: provision the same two users in public
-- as well. AbstractIntegrationTest#cleanDatabase() deletes every public user
-- before each test method, which is what makes them absent there.
--
-- Fully qualified, guarded and idempotent: on a public-target run these are
-- no-ops because the unqualified block above already inserted (or V56/V58
-- already owned) the same UUIDs. Fixture-only data; retention in the
-- throwaway Testcontainers database.
-- ---------------------------------------------------------------------------

INSERT INTO public.users (id, email, password_hash, display_name, status, email_verified, email_verified_at, created_at, updated_at)
SELECT '90000000-0000-0000-0000-000000000023', 'v86-fixture-doctor@healthcare.local', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ThS.BS Trần Thu Hà', 'ACTIVE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM public.users WHERE id = '90000000-0000-0000-0000-000000000023')
ON CONFLICT DO NOTHING;

INSERT INTO public.user_roles (user_id, role_id)
SELECT '90000000-0000-0000-0000-000000000023', r.id FROM public.roles r WHERE r.code = 'DOCTOR'
ON CONFLICT DO NOTHING;

INSERT INTO public.users (id, email, password_hash, display_name, status, email_verified, email_verified_at, created_at, updated_at)
SELECT '90000000-0000-0000-0000-000000000002', 'v86-fixture-reviewer@healthcare.local', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'BS Nguyễn Quốc Trọng', 'ACTIVE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM public.users WHERE id = '90000000-0000-0000-0000-000000000002')
ON CONFLICT DO NOTHING;

INSERT INTO public.user_roles (user_id, role_id)
SELECT '90000000-0000-0000-0000-000000000002', r.id FROM public.roles r WHERE r.code = 'DOCTOR'
ON CONFLICT DO NOTHING;
