#!/usr/bin/env python3
"""Generate deterministic, idempotent SQL chunks for the Supabase mirror.

The generated SQL is intentionally set-based: PostgreSQL expands each range
with generate_series instead of receiving one INSERT statement per row. The
manifest is immutable apart from per-chunk status, so a failed run can resume
from the first incomplete chunk without deleting existing data.

This tool only produces fictional catalog/customer/profile data. It never
reads a patient source, accepts a patient file, or emits credentials.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import tempfile
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


MANIFEST_VERSION = 1
DEFAULT_DATASET_KEY = "healthcare.synthetic"
DEFAULT_DATASET_VERSION = "v2-100k-75k-10k"
DEFAULT_SEED = 20260823
DEFAULT_CUSTOMERS = 100_000
DEFAULT_PATIENT_PROFILES = 75_000
DEFAULT_PUBLIC_RAG_DOCUMENTS = 10_000
DEFAULT_CATALOG_BASELINE = 1_480
DEFAULT_CHUNK_SIZE = 5_000
ENTITY_ORDER = ("CUSTOMER", "PATIENT_PROFILE", "PUBLIC_RAG_DOCUMENT")
SAFE_NAME = re.compile(r"^[A-Za-z0-9._:-]+$")


@dataclass(frozen=True)
class Chunk:
    entity_type: str
    chunk_no: int
    range_start: int
    range_end: int
    expected_rows: int
    sql_file: str


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("value must be >= 1")
    return parsed


def non_negative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("value must be >= 0")
    return parsed


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def canonical_json(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":")) + "\n").encode(
        "utf-8"
    )


def chunk_ranges(total: int, chunk_size: int) -> Iterable[tuple[int, int, int]]:
    chunk_no = 1
    start = 1
    while start <= total:
        end = min(start + chunk_size - 1, total)
        yield chunk_no, start, end
        chunk_no += 1
        start = end + 1


def validate_config(args: argparse.Namespace) -> None:
    if not SAFE_NAME.fullmatch(args.dataset_key):
        raise ValueError("dataset-key may contain only letters, digits, '.', '_', ':' and '-'")
    if not SAFE_NAME.fullmatch(args.dataset_version):
        raise ValueError("dataset-version may contain only letters, digits, '.', '_', ':' and '-'")
    if args.patient_profiles > args.customers:
        raise ValueError("patient-profiles cannot exceed customers")
    if args.public_rag_documents < args.catalog_baseline:
        raise ValueError("public-rag-documents must include the existing catalog baseline")


def build_chunks(args: argparse.Namespace) -> list[Chunk]:
    specs: list[Chunk] = []
    targets = (
        ("CUSTOMER", args.customers),
        ("PATIENT_PROFILE", args.patient_profiles),
        ("PUBLIC_RAG_DOCUMENT", args.public_rag_documents - args.catalog_baseline),
    )
    for entity_type, total in targets:
        for chunk_no, start, end in chunk_ranges(total, args.chunk_size):
            prefix = {
                "CUSTOMER": "customers",
                "PATIENT_PROFILE": "patient-profiles",
                "PUBLIC_RAG_DOCUMENT": "public-rag-documents",
            }[entity_type]
            specs.append(
                Chunk(
                    entity_type=entity_type,
                    chunk_no=chunk_no,
                    range_start=start,
                    range_end=end,
                    expected_rows=end - start + 1,
                    sql_file=f"chunks/{prefix}-{chunk_no:04d}.sql",
                )
            )
    return specs


def sql_header(chunk: Chunk, args: argparse.Namespace) -> str:
    return f"""-- Generated by supabase/tools/generate_synthetic_data.py.
-- Dataset: {args.dataset_key}/{args.dataset_version}; seed: {args.seed}.
-- Entity: {chunk.entity_type}; range: {chunk.range_start}-{chunk.range_end}.
-- Synthetic only. Do not run against a production database without review.
\\set ON_ERROR_STOP on
set search_path = healthcare, extensions, public;
begin;
"""


def customer_sql(chunk: Chunk, args: argparse.Namespace) -> str:
    return (
        sql_header(chunk, args)
        + f"""insert into healthcare.customers (
    id, customer_code, legacy_user_id, auth_user_id, full_name, email,
    phone, status, synthetic
)
select md5('supabase-customer:' || i::text)::uuid,
       'KH-' || lpad(i::text, 6, '0'),
       md5('large-user:' || i::text)::uuid,
       null,
       'Synthetic customer ' || i,
       'customer' || i || '@healthcare.local',
       '09' || lpad(i::text, 8, '0'),
       case
           when i % 50 = 0 then 'DISABLED'
           when i % 13 = 0 then 'PENDING'
           else 'ACTIVE'
       end,
       true
from generate_series({chunk.range_start}, {chunk.range_end}) as g(i)
on conflict (customer_code) do nothing;
commit;
"""
    )


def patient_profile_sql(chunk: Chunk, args: argparse.Namespace) -> str:
    return (
        sql_header(chunk, args)
        + f"""insert into healthcare.patient_profiles (
    id, customer_id, legacy_patient_profile_id, date_of_birth, gender,
    address, emergency_contact_name, emergency_contact_phone
)
select md5('supabase-patient-profile:' || c.id::text)::uuid,
       c.id,
       md5('large-patient:' || c.legacy_user_id::text)::uuid,
       (date '1980-01-01' + ((abs(hashtextextended(c.id::text, {args.seed})) % 12000) || ' days')::interval)::date,
       case (abs(hashtextextended(c.id::text, {args.seed})) % 4)
           when 0 then 'MALE'
           when 1 then 'FEMALE'
           when 2 then 'OTHER'
           else 'UNSPECIFIED'
       end,
       'Synthetic address ' || (abs(hashtextextended(c.id::text, {args.seed})) % 1000 + 1),
       'Synthetic contact ' || (abs(hashtextextended(c.id::text, {args.seed})) % 100 + 1),
       '09' || lpad(replace(c.customer_code, 'KH-', ''), 8, '0')
from healthcare.customers c
where substring(c.customer_code from 4)::bigint between {chunk.range_start} and {chunk.range_end}
on conflict (customer_id) do nothing;
commit;
"""
    )


def rag_sql(chunk: Chunk, args: argparse.Namespace) -> str:
    dataset_key = sql_literal(args.dataset_key)
    dataset_version = sql_literal(args.dataset_version)
    return (
        sql_header(chunk, args)
        + f"""do $$
begin
    if (
        select count(*)
        from healthcare.ai_documents
        where source_id not like 'synthetic-article-%'
    ) <> {args.catalog_baseline} then
        raise exception 'catalog baseline mismatch; expected {args.catalog_baseline} non-generated documents';
    end if;
end;
$$;

with generated_rows as (
    select i,
           'Synthetic public health article ' || i::text as title,
           'Fictional public catalog guidance for load testing, entry ' || i::text
               || '. This content contains no patient data and is not clinical advice.' as content
    from generate_series({chunk.range_start}, {chunk.range_end}) as g(i)
)
insert into healthcare.ai_documents (
    source_type, source_id, title, content, metadata, embedding,
    embedding_model, embedding_dimension, embedding_provenance,
    content_hash, sync_revision, active, published, published_at, deleted_at
)
select
    'article',
    'synthetic-article-' || lpad(i::text, 6, '0'),
    title,
    content,
    jsonb_build_object(
        'dataset_key', {dataset_key},
        'dataset_version', {dataset_version},
        'synthetic', true,
        'category', 'article'
    ),
    healthcare.synthetic_embedding('synthetic-article:' || i::text),
    'local-hash',
    384,
    'local_provider',
    encode(extensions.digest(content, 'sha256'), 'hex'),
    1,
    true,
    true,
    timestamptz '2026-01-01T00:00:00+07:00'
        + ((i % 365) || ' days')::interval,
    null
from generated_rows
on conflict (source_type, source_id) do update
set title = excluded.title,
    content = excluded.content,
    metadata = excluded.metadata,
    embedding = excluded.embedding,
    embedding_model = excluded.embedding_model,
    embedding_dimension = excluded.embedding_dimension,
    embedding_provenance = excluded.embedding_provenance,
    content_hash = excluded.content_hash,
    sync_revision = excluded.sync_revision,
    active = excluded.active,
    published = excluded.published,
    published_at = excluded.published_at,
    deleted_at = excluded.deleted_at;
commit;
"""
    )


def render_chunk(chunk: Chunk, args: argparse.Namespace) -> str:
    if chunk.entity_type == "CUSTOMER":
        return customer_sql(chunk, args)
    if chunk.entity_type == "PATIENT_PROFILE":
        return patient_profile_sql(chunk, args)
    if chunk.entity_type == "PUBLIC_RAG_DOCUMENT":
        return rag_sql(chunk, args)
    raise ValueError(f"unsupported entity type: {chunk.entity_type}")


def immutable_config(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "manifest_version": MANIFEST_VERSION,
        "dataset_key": args.dataset_key,
        "dataset_version": args.dataset_version,
        "seed": args.seed,
        "targets": {
            "customers": args.customers,
            "patient_profiles": args.patient_profiles,
            "public_rag_documents": args.public_rag_documents,
        },
        "catalog_baseline": args.catalog_baseline,
        "chunk_size": args.chunk_size,
        "embedding_dimension": 384,
        "embedding_model": "local-hash",
        "embedding_provenance": "local_provider",
        "run_id": deterministic_run_id(args),
    }


def deterministic_run_id(args: argparse.Namespace) -> str:
    value = f"synthetic-seed-run:{args.dataset_key}:{args.dataset_version}:{args.seed}".encode(
        "utf-8"
    )
    return str(uuid.UUID(bytes=hashlib.md5(value).digest()))


def manifest_hash(config: dict[str, Any], chunks: list[dict[str, Any]]) -> str:
    return sha256_bytes(canonical_json({"config": config, "chunks": chunks}))


def read_manifest(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read manifest: {path}: {exc}") from exc
    if value.get("manifest_version") != MANIFEST_VERSION:
        raise ValueError("unsupported manifest version")
    return value


def write_json_atomic(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = canonical_json(value)
    with tempfile.NamedTemporaryFile(
        mode="wb", dir=path.parent, prefix=f".{path.name}.", suffix=".tmp", delete=False
    ) as handle:
        temporary = Path(handle.name)
        handle.write(payload)
    temporary.replace(path)


def build_manifest(args: argparse.Namespace, chunks: list[Chunk], output_dir: Path) -> dict[str, Any]:
    rendered: list[dict[str, Any]] = []
    for chunk in chunks:
        sql = render_chunk(chunk, args).encode("utf-8")
        rendered.append(
            {
                "entity_type": chunk.entity_type,
                "chunk_no": chunk.chunk_no,
                "range_start": chunk.range_start,
                "range_end": chunk.range_end,
                "expected_rows": chunk.expected_rows,
                "sql_file": chunk.sql_file,
                "sha256": sha256_bytes(sql),
                "status": "PENDING",
            }
        )
    config = immutable_config(args)
    return {
        **config,
        "manifest_hash": manifest_hash(config, rendered),
        "created_at": utc_now(),
        "chunks": rendered,
    }


def validate_existing_manifest(existing: dict[str, Any], expected: dict[str, Any]) -> None:
    for key in expected:
        if existing.get(key) != expected[key]:
            raise ValueError(f"existing manifest does not match requested {key}")
    if not isinstance(existing.get("chunks"), list):
        raise ValueError("manifest chunks must be an array")


def write_or_resume(args: argparse.Namespace) -> tuple[Path, dict[str, Any], int]:
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / "manifest.json"
    chunks = build_chunks(args)
    expected_config = immutable_config(args)
    expected_manifest = build_manifest(args, chunks, output_dir)

    if manifest_path.exists():
        manifest = read_manifest(manifest_path)
        validate_existing_manifest(manifest, expected_config)
        if manifest.get("manifest_hash") != expected_manifest["manifest_hash"]:
            raise ValueError("existing manifest chunk contract differs; use a new output directory")
    else:
        manifest = expected_manifest

    changed = 0
    by_file = {entry["sql_file"]: entry for entry in manifest["chunks"]}
    for chunk in chunks:
        entry = by_file[chunk.sql_file]
        destination = output_dir / chunk.sql_file
        destination.parent.mkdir(parents=True, exist_ok=True)
        expected_sql = render_chunk(chunk, args).encode("utf-8")
        if destination.exists():
            actual = destination.read_bytes()
            if sha256_bytes(actual) != entry["sha256"]:
                raise ValueError(f"chunk checksum mismatch: {destination}")
        else:
            destination.write_bytes(expected_sql)
            entry["status"] = "PENDING"
            changed += 1

    write_json_atomic(manifest_path, manifest)
    return manifest_path, manifest, changed


def redact_error(value: str) -> str:
    value = re.sub(r"(?i)(postgres(?:ql)?://)[^\s]+", r"\1<redacted>", value)
    value = re.sub(r"(?i)(password|secret|token|api[_-]?key)\s*[:=]\s*[^\s]+", r"\1=<redacted>", value)
    return value.replace("\x00", " ")[-1000:]


def checkpoint_start_sql(manifest: dict[str, Any], entry: dict[str, Any]) -> str:
    targets = manifest["targets"]
    run_id = sql_literal(manifest["run_id"])
    dataset_key = sql_literal(manifest["dataset_key"])
    dataset_version = sql_literal(manifest["dataset_version"])
    entity_type = sql_literal(entry["entity_type"])
    checksum = sql_literal(entry["sha256"])
    return f"""insert into healthcare.synthetic_seed_runs (
    id, dataset_key, dataset_version, seed,
    target_customers, target_patient_profiles, target_public_rag_documents,
    chunk_size, manifest_hash, status, started_at
)
values (
    {run_id}::uuid,
    {dataset_key},
    {dataset_version},
    {manifest["seed"]},
    {targets["customers"]},
    {targets["patient_profiles"]},
    {targets["public_rag_documents"]},
    {manifest["chunk_size"]},
    {sql_literal(manifest["manifest_hash"])},
    'RUNNING',
    coalesce((select started_at from healthcare.synthetic_seed_runs where id = {run_id}::uuid), now())
)
on conflict (dataset_key, dataset_version, seed) do update
set manifest_hash = excluded.manifest_hash,
    status = 'RUNNING',
    started_at = coalesce(healthcare.synthetic_seed_runs.started_at, excluded.started_at),
    completed_at = null;

insert into healthcare.synthetic_seed_chunks (
    id, run_id, entity_type, chunk_no, range_start, range_end,
    expected_rows, processed_rows, status, checksum, error_message, started_at
)
values (
    md5('synthetic-seed-chunk:' || {run_id} || ':' || {entity_type} || ':' || {entry["chunk_no"]})::uuid,
    {run_id}::uuid,
    {entity_type},
    {entry["chunk_no"]},
    {entry["range_start"]},
    {entry["range_end"]},
    {entry["expected_rows"]},
    0,
    'RUNNING',
    {checksum},
    null,
    now()
)
on conflict (run_id, entity_type, chunk_no) do update
set range_start = excluded.range_start,
    range_end = excluded.range_end,
    expected_rows = excluded.expected_rows,
    processed_rows = 0,
    status = 'RUNNING',
    checksum = excluded.checksum,
    error_message = null,
    started_at = now(),
    completed_at = null;
"""


def checkpoint_complete_sql(manifest: dict[str, Any], entry: dict[str, Any]) -> str:
    return f"""update healthcare.synthetic_seed_chunks
set processed_rows = expected_rows,
    status = 'COMPLETED',
    completed_at = now(),
    error_message = null
where run_id = {sql_literal(manifest["run_id"])}::uuid
  and entity_type = {sql_literal(entry["entity_type"])}
  and chunk_no = {entry["chunk_no"]};

update healthcare.synthetic_seed_runs
set status = case
        when not exists (
            select 1 from healthcare.synthetic_seed_chunks
            where run_id = {sql_literal(manifest["run_id"])}::uuid
              and status <> 'COMPLETED'
        ) then 'COMPLETED'
        else 'RUNNING'
    end,
    completed_at = case
        when not exists (
            select 1 from healthcare.synthetic_seed_chunks
            where run_id = {sql_literal(manifest["run_id"])}::uuid
              and status <> 'COMPLETED'
        ) then now()
        else null
    end
where id = {sql_literal(manifest["run_id"])}::uuid;
"""


def checkpoint_failed_sql(manifest: dict[str, Any], entry: dict[str, Any], error: str) -> str:
    return f"""update healthcare.synthetic_seed_chunks
set status = 'FAILED',
    error_message = {sql_literal(redact_error(error))}
where run_id = {sql_literal(manifest["run_id"])}::uuid
  and entity_type = {sql_literal(entry["entity_type"])}
  and chunk_no = {entry["chunk_no"]};
update healthcare.synthetic_seed_runs
set status = 'FAILED', completed_at = null
where id = {sql_literal(manifest["run_id"])}::uuid;
"""


def run_psql(psql_bin: str, database_url: str, *options: str) -> subprocess.CompletedProcess[str]:
    command = [
        psql_bin,
        "--no-psqlrc",
        "--dbname",
        database_url,
        "--set",
        "ON_ERROR_STOP=1",
        *options,
    ]
    return subprocess.run(command, capture_output=True, text=True, check=False)


def apply_manifest(args: argparse.Namespace) -> int:
    manifest_path = Path(args.manifest).expanduser().resolve()
    manifest = read_manifest(manifest_path)
    output_dir = manifest_path.parent
    database_url = os.environ.get(args.database_url_env, "")
    if not database_url:
        raise ValueError(f"required database URL environment variable is missing: {args.database_url_env}")

    for entry in manifest["chunks"]:
        chunk_path = output_dir / entry["sql_file"]
        if not chunk_path.exists() or sha256_bytes(chunk_path.read_bytes()) != entry["sha256"]:
            raise ValueError(f"chunk checksum mismatch: {chunk_path}")
        if entry["status"] == "COMPLETED":
            continue
        if args.dry_run:
            continue
        started = run_psql(
            args.psql_bin,
            database_url,
            "--command",
            checkpoint_start_sql(manifest, entry),
        )
        if started.returncode != 0:
            entry["status"] = "FAILED"
            entry["error"] = redact_error(started.stderr or started.stdout or "checkpoint start failed")
            manifest["status"] = "FAILED"
            write_json_atomic(manifest_path, manifest)
            return 1

        result = run_psql(args.psql_bin, database_url, "--file", str(chunk_path))
        if result.returncode != 0:
            entry["status"] = "FAILED"
            entry["error"] = redact_error(result.stderr or result.stdout or "psql failed")
            failed = run_psql(
                args.psql_bin,
                database_url,
                "--command",
                checkpoint_failed_sql(manifest, entry, entry["error"]),
            )
            if failed.returncode != 0:
                entry["error"] += "; checkpoint failure could not be recorded"
            manifest["status"] = "FAILED"
            write_json_atomic(manifest_path, manifest)
            return 1

        completed = run_psql(
            args.psql_bin,
            database_url,
            "--command",
            checkpoint_complete_sql(manifest, entry),
        )
        if completed.returncode != 0:
            entry["status"] = "FAILED"
            entry["error"] = redact_error(
                completed.stderr or completed.stdout or "checkpoint completion failed"
            )
            manifest["status"] = "FAILED"
            write_json_atomic(manifest_path, manifest)
            return 1
        entry["status"] = "COMPLETED"
        entry.pop("error", None)
        write_json_atomic(manifest_path, manifest)

    if not args.dry_run:
        manifest["status"] = "COMPLETED"
        write_json_atomic(manifest_path, manifest)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser("generate", help="write deterministic SQL chunks and a manifest")
    generate.add_argument("--output-dir", required=True, help="dedicated output directory")
    generate.add_argument("--dataset-key", default=DEFAULT_DATASET_KEY)
    generate.add_argument("--dataset-version", default=DEFAULT_DATASET_VERSION)
    generate.add_argument("--seed", type=int, default=DEFAULT_SEED)
    generate.add_argument("--customers", type=positive_int, default=DEFAULT_CUSTOMERS)
    generate.add_argument("--patient-profiles", type=positive_int, default=DEFAULT_PATIENT_PROFILES)
    generate.add_argument("--public-rag-documents", type=positive_int, default=DEFAULT_PUBLIC_RAG_DOCUMENTS)
    generate.add_argument("--catalog-baseline", type=non_negative_int, default=DEFAULT_CATALOG_BASELINE)
    generate.add_argument("--chunk-size", type=positive_int, default=DEFAULT_CHUNK_SIZE)

    apply = subparsers.add_parser("apply", help="apply pending chunks through psql")
    apply.add_argument("--manifest", required=True)
    apply.add_argument("--database-url-env", default="SUPABASE_DB_URL")
    apply.add_argument("--psql-bin", default="psql")
    apply.add_argument("--dry-run", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "generate":
            validate_config(args)
            manifest_path, manifest, changed = write_or_resume(args)
            print(
                f"generated manifest={manifest_path} chunks={len(manifest['chunks'])} "
                f"new_files={changed} manifest_hash={manifest['manifest_hash']}"
            )
            return 0
        return apply_manifest(args)
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        parser.error(str(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
