#!/usr/bin/env python3
"""Generate the project-local OpenCode subagent adapter.

The 17 AgentKit specialists (name, description, skills, role, temperature,
max turns) are owned by generate-gemini-adapter.py and imported by path so the
Gemini and OpenCode adapters cannot drift. OpenCode additionally consumes
`.agents/skills` natively and exposes every skill as an `/ak:<name>` command,
so this adapter deliberately generates no per-skill command files and no
`.opencode/skills` mirror; a second copy would duplicate the `/ak:` namespace.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parents[2]
SKILLS_ROOT = ROOT / ".agents" / "skills"
AGENTS_ROOT = ROOT / ".opencode" / "agents"
CONFIG_PATH = ROOT / ".opencode" / "opencode.json"
OPENCODE_MD_PATH = ROOT / "OPENCODE.md"
GENERATED_MARKER = "Generated by engineer/.agentkit/scripts/generate-opencode-adapter.py"


def load_gemini_module():
    source = SCRIPT_DIR / "generate-gemini-adapter.py"
    spec = importlib.util.spec_from_file_location("agentkit_gemini_adapter", source)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {source}")
    module = importlib.util.module_from_spec(spec)
    # dataclass processing resolves the module through sys.modules.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def agent_bytes(agent) -> bytes:
    skill_lines = "\n".join(f"- `.agents/skills/{skill}/SKILL.md`" for skill in agent.skills)
    body = f'''---
description: {agent.description}
mode: subagent
temperature: {agent.temperature}
steps: {agent.max_turns}
---

<!-- {GENERATED_MARKER} -->
# AgentKit {agent.name}

You are the AgentKit `{agent.name}` specialist running as an OpenCode project
subagent. Complete only the bounded assignment passed by the controller and
return a concise evidence-based result.

## Required skill loading

The project contract lives in the root `AGENTS.md` and `OPENCODE.md`; honor it
when already in context and read it from the project root otherwise. Then read
these project-local skill entrypoints in order:

{skill_lines}

Project-local `.agents/skills` content is authoritative. Do not silently fall
back to a global Claude, Codex, Cursor, Gemini, or OpenCode installation. If a
required entrypoint is absent, report `AGENTKIT_SKILL_NOT_FOUND` with the
missing relative path and stop.

## Role boundary

{agent.role}

Preserve unrelated user work. Treat `BLOCKED` and `NOT_RUN` as evidence states,
not success. Include the files inspected or changed, commands actually run, test
results, and residual limitations in the handoff.
'''
    return body.encode("utf-8")


CONFIG_OBJECT = {
    "$schema": "https://opencode.ai/config.json",
    "instructions": ["OPENCODE.md"],
}


OPENCODE_MD = f'''# AgentKit for OpenCode

This project includes the AgentKit workflow system for OpenCode. Treat
project-local files as authoritative and keep all behavior portable across
machines and project roots.

## Runtime assets

- Skills: `.agents/skills/**/SKILL.md` — OpenCode discovers this shared
  registry natively, exposes every skill through its `skill` tool, and lists
  each one as an `/ak:<name>` command. `ak:common` is an internal helper that
  also appears in that list; it is not a user entrypoint.
- Subagents: `.opencode/agents/*.md`, invocable with `@agent-name` in the
  composer or delegated by the primary agent through the task tool.
- OpenCode adapter config: `.opencode/opencode.json` (loads this file as an
  instruction; it must stay free of model, theme, and credential settings).
- AgentKit preferences and project helpers: `.agentkit/`
- Project-wide contributor rules: `AGENTS.md` — OpenCode reads it natively.

There is intentionally no `.opencode/skills` mirror and no per-skill
`.opencode/commands` files: OpenCode already consumes `.agents/skills`, and a
second copy would duplicate every `/ak:*` entry. Do not search a user-global
Claude, Codex, Cursor, Gemini, or OpenCode installation before the
project-local AgentKit assets. If a required project entrypoint is missing,
report the exact relative path and stop instead of silently using a stale
global copy.

## Workflow routing

1. Read this file and the nearest applicable `AGENTS.md` before changing files.
2. Match the request to an AgentKit skill. Prefer `/ak:agentkit` when routing is
   unclear and `/ak:help` when the user asks what is available.
3. Read the selected `SKILL.md` completely and follow its referenced resources
   as required.
4. For implementation, preserve unrelated work, plan before multi-file changes,
   make focused edits, and verify proportionally.
5. Use specialist subagents when their description matches the bounded task.
   OpenCode subagents get one bounded assignment; the controller owns
   orchestration and cross-agent handoffs.
6. Treat `BLOCKED` and `NOT_RUN` as evidence states, never as `PASS`.

## Common commands

- `/ak:agentkit <task>` — route a complex or unclear request
- `/ak:plan <task>` — create a file-first implementation plan
- `/ak:cook <plan or task>` — implement through the AgentKit workflow
- `/ak:debug <failure>` — reproduce and isolate a root cause
- `/ak:test <scope>` — run focused verification
- `/ak:code-review <scope>` — independent code review
- `/ak:git <operation>` — focused Git operations
- `/ak:help` — inspect the full AgentKit catalog

Every public AgentKit skill also has a matching `/ak:<skill>` command.

## Safety and delivery rules

- Resolve paths relative to the workspace; never write a machine-specific path
  into project assets.
- Do not edit global kit installations unless the user explicitly names them as
  the target.
- Never discard a dirty worktree, reset unrelated changes, or stage files
  outside the requested scope.
- Do not claim a commit was pushed until the remote ref is independently checked.
- Do not claim live, browser, deployment, provider, or cross-platform behavior
  from static/unit evidence alone.
- Do not expose secrets, tokens, credentials, private host paths, or raw auth
  errors in reports or commits.
- OpenCode provider authentication belongs to the machine/user environment,
  never `.opencode/opencode.json` in the repository.
- The OpenCode adapter has no reviewed active-plan session-state bridge. The
  `.agentkit` wrapper validates plan structure and containment but must report
  validation-only instead of claiming persistence.

## Catalog refresh

OpenCode discovers project skills, subagents, and config when a session starts.
After copying or updating this adapter, start a new session from the project
root or restart OpenCode. Trust the project only after reviewing the copied
files.
'''


def expected_files():
    gemini = load_gemini_module()
    expected = {AGENTS_ROOT / f"{agent.name}.md": agent_bytes(agent) for agent in gemini.AGENTS}
    expected[CONFIG_PATH] = (
        json.dumps(CONFIG_OBJECT, indent=2, ensure_ascii=False) + "\n"
    ).encode("utf-8")
    expected[OPENCODE_MD_PATH] = OPENCODE_MD.encode("utf-8")
    return gemini, expected


def canonical_bytes(data: bytes) -> bytes:
    # Git checkouts with core.autocrlf materialize CRLF; generated content is
    # authored with LF. Normalize before comparing so a Windows checkout does
    # not look stale solely because of line endings (same contract as
    # generate-install-manifest.py).
    return data.replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def check(gemini, expected: dict[Path, bytes]) -> int:
    actual = set(AGENTS_ROOT.glob("*.md")) if AGENTS_ROOT.exists() else set()
    actual.update(path for path in (CONFIG_PATH, OPENCODE_MD_PATH) if path.is_file())
    expected_paths = set(expected)
    errors: list[str] = []
    for path in sorted(expected_paths - actual):
        errors.append(f"missing: {path.relative_to(ROOT)}")
    for path in sorted(actual - expected_paths):
        errors.append(f"unexpected: {path.relative_to(ROOT)}")
    for path in sorted(actual & expected_paths):
        if canonical_bytes(path.read_bytes()) != canonical_bytes(expected[path]):
            errors.append(f"stale: {path.relative_to(ROOT)}")
    for forbidden in (
        ROOT / ".opencode" / "skills",
        ROOT / ".opencode" / "command",
        ROOT / ".opencode" / "commands",
    ):
        if forbidden.exists():
            errors.append(f"forbidden duplicate registry: {forbidden.relative_to(ROOT)}")
    if errors:
        print("OpenCode adapter is out of date:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(
        f"OpenCode adapter is current: {len(gemini.AGENTS)} agents, "
        f"{len(gemini.public_skills())} skills consumed via .agents/skills"
    )
    return 0


def write(gemini, expected: dict[Path, bytes]) -> int:
    AGENTS_ROOT.mkdir(parents=True, exist_ok=True)
    for path in AGENTS_ROOT.glob("*.md"):
        if path not in expected and GENERATED_MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
    for path, content in sorted(expected.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    print(f"Generated {len(gemini.AGENTS)} OpenCode agents, opencode.json, and OPENCODE.md")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check generated files without writing")
    args = parser.parse_args()
    gemini, expected = expected_files()
    return check(gemini, expected) if args.check else write(gemini, expected)


if __name__ == "__main__":
    raise SystemExit(main())
