"""Regenerate the V86/V87 catalog fixture deterministically.

Why this exists: migrations V86/V87 insert appointments (and dependent rows)
whose branch/doctor/package/specialty IDs must already exist. A production
database acquired those rows through the admin CMS before the migrations ran,
and the migration chain never creates them, so the integration suite could not
boot on a fresh database. The fixture is executed by CatalogFixtureCallback
immediately before V86. This generator makes the fixture reproducible instead
of hand-edited:

    python scripts/generate-v86-fixture.py            # rewrite the fixture
    python scripts/generate-v86-fixture.py --check    # verify it is current

Sources are the same local-dev repair scripts that were validated against a
real PostgreSQL 18 database, plus the (doctor_id, branch_id) pairs derived from
the migrations themselves with a whitespace-tolerant parser.
"""
import io
import os
import re
import sys

FIXTURE = "apps/backend/src/main/resources/db/catalog/v86-catalog-prerequisites.sql"
REPAIR = "scripts/local-dev-repair"
MIGRATIONS = "apps/backend/src/main/resources/db/migration"
UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

HEADER = """-- Test fixture: catalog rows that migrations V86/V87 reference by fixed UUID.
--
-- Generated by scripts/generate-v86-fixture.py -- do not edit by hand.
--
-- V86 seeds appointments whose branch_id/doctor_id/package_id must already
-- exist; V87 adds more of the same. Production supplies those rows through the
-- admin CMS at runtime, and the migration chain on an EMPTY database was never
-- exercised, so the integration suite could not boot. CatalogFixtureCallback
-- executes this fixture immediately before V86; it is idempotent and a no-op
-- once the rows exist.
--
-- Row values are production-identical public catalog data.
"""


def read(path):
    return io.open(path, encoding="utf-8").read()


def strip_search_path(sql):
    """Drop ``SET search_path`` lines from a source section.

    The repair scripts pin search_path for manual psql use; inside the fixture
    that would move every following statement (doctor_branches, cms, packages)
    to the public schema while FlywayMigrationTest runs V86 in an isolated
    schema, so the fixture would insert rows V86 never sees.
    """
    return "\n".join(l for l in sql.splitlines() if not l.strip().lower().startswith("set search_path"))


def referenced_pairs(text):
    out = set()
    for match in re.finditer(
        r"INSERT INTO appointments \(([^)]*)\)\s*VALUES\s*\(([^;]*?)\)\s*ON CONFLICT", text, re.S
    ):
        cols = [c.strip() for c in match.group(1).split(",")]
        parts, cur, quoted = [], "", False
        for ch in match.group(2):
            if ch == "'":
                quoted = not quoted
            if ch == "," and not quoted:
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        parts.append(cur)
        if len(parts) != len(cols):
            continue
        row = dict(zip(cols, [p.strip().strip("'") for p in parts]))
        doctor, branch = row.get("doctor_id", ""), row.get("branch_id", "")
        if re.match("^" + UUID + "$", doctor) and re.match("^" + UUID + "$", branch):
            out.add((doctor, branch))
    return out


def branch_section():
    """Rewrite the plain branch inserts into slug-conflict-safe inserts.

    Earlier migrations (e.g. V67) seed demo branches whose slugs (cs-N)
    collide with the production-identical slugs here; the original
    ON CONFLICT (slug) DO NOTHING silently skipped the row, so the FK rows
    V86/V87 reference by fixed UUID never existed and doctor_branches failed.
    """
    source = read(f"{REPAIR}/03-specialties-and-branches-v1.sql")
    pattern = re.compile(
        r"INSERT INTO branches \(id, name, slug, address, phone, working_hours, active\) VALUES "
        r"\('(" + UUID + r")', '([^']*)', '([^']*)', '([^']*)', '([^']*)', '([^']*)', true\) "
        r"ON CONFLICT \(id\) DO NOTHING;"
    )
    lines = []
    for match in pattern.finditer(source):
        bid, name, slug, address, phone, hours = match.groups()
        lines.append(
            "INSERT INTO branches (id, name, slug, address, phone, working_hours, active)\n"
            f"SELECT '{bid}', '{name}', CASE WHEN EXISTS (SELECT 1 FROM branches WHERE slug = '{slug}' AND id <> '{bid}') THEN '{slug}-imp' ELSE '{slug}' END, '{address}', '{phone}', '{hours}', true\n"
            f"WHERE NOT EXISTS (SELECT 1 FROM branches WHERE id = '{bid}');"
        )
    if not lines:
        raise SystemExit("branch_section: no branch rows matched -- repair script changed shape")
    return "\n".join(lines), len(lines)


def build():
    branch_sql, _ = branch_section()
    specialties = strip_search_path(read(f"{REPAIR}/04-specialties-idempotent.sql"))
    doctors = strip_search_path(read(f"{REPAIR}/02-doctors-from-prod-catalog.sql"))
    packages = strip_search_path(read(f"{REPAIR}/06-packages-from-prod.sql"))
    cms_contents = strip_search_path(read(f"{REPAIR}/07-cms-contents-for-v86.sql"))

    v86 = read(f"{MIGRATIONS}/V86__seed_comprehensive_clinical_tables_and_empty_tables.sql")
    v87 = read(f"{MIGRATIONS}/V87__enrich_clinical_enterprise_big_data.sql")
    pairs = sorted(referenced_pairs(v86) | referenced_pairs(v87))
    pair_sql = "\n".join(
        "INSERT INTO doctor_branches (id, doctor_id, branch_id)\n"
        f"SELECT md5('fixture:{doctor}:{branch}')::uuid, '{doctor}', '{branch}'\n"
        "WHERE NOT EXISTS (SELECT 1 FROM doctor_branches\n"
        f"   WHERE doctor_id = '{doctor}' AND branch_id = '{branch}');"
        for doctor, branch in pairs
    )
    sections = [HEADER, branch_sql, specialties.strip(), doctors.strip(), pair_sql, cms_contents.strip(), packages.strip()]
    return "\n\n".join(section for section in sections if section) + "\n", len(pairs)


def main():
    content, pair_count = build()
    current = read(FIXTURE) if os.path.exists(FIXTURE) else ""
    if "--check" in sys.argv:
        if current == content:
            print(f"fixture is current ({pair_count} doctor-branch pairs)")
            return 0
        print("fixture is STALE -- run: python scripts/generate-v86-fixture.py")
        return 1
    io.open(FIXTURE, "w", encoding="utf-8").write(content)
    print(f"fixture written: {len(content)} chars, {pair_count} doctor-branch pairs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
