/**
 * HealthCare Hospital Event & Community Activities Visual Catalog
 *
 * Dedicated image registry and visual metadata for hospital events,
 * scientific conferences, medical charity screenings, public health campaigns,
 * and academic seminars.
 */

export interface EventVisual {
  id: string;
  title: string;
  category: EventCategory;
  categoryLabel: string;
  imageSrc: string;
  imageAlt: string;
  description: string;
  tag: string;
  dateBadge: string;
  location: string;
}

export type EventCategory =
  | "conference"
  | "charity"
  | "blood_donation"
  | "anniversary"
  | "public_health"
  | "internal_life";

export const HOSPITAL_EVENTS_CATALOG: readonly EventVisual[] = [
  // ==========================================
  // 1. Hội thảo khoa học, Tọa đàm & Đào tạo CME
  // ==========================================
  {
    id: "hoi-nghi-khoa-hoc-y-te",
    title: "Hội Nghị Khoa Học Y Tế Thường Niên & Cập Nhật Điều Trị Bệnh Tim Mạch",
    category: "conference",
    categoryLabel: "Hội Nghị Khoa Học",
    imageSrc: "/media/events/hoi-nghi-khoa-hoc-y-te.jpg",
    imageAlt: "Toàn cảnh hội trường hội nghị khoa học y tế với bài thuyết trình điều trị tim mạch",
    description: "Quy tụ hàng trăm chuyên gia đầu ngành trong và ngoài nước chia sẻ các tiến bộ lâm sàng tim mạch học mới nhất.",
    tag: "SỰ KIỆN TRỌNG ĐIỂM",
    dateBadge: "Thường niên",
    location: "Hội trường Grand Hall - Bệnh viện Đa khoa HealthCare",
  },
  {
    id: "tap-huan-phau-thuat-cme",
    title: "Khóa Đào Tạo Y Khoa Liên Tục (CME): Phẫu Thuật Nội Soi Nâng Cao",
    category: "conference",
    categoryLabel: "Đào Tạo CME",
    imageSrc: "/media/events/tap-huan-phau-thuat-cme.jpg",
    imageAlt: "Bác sĩ hướng dẫn thực hành kỹ thuật phẫu thuật nội soi trên mô hình mô phỏng",
    description: "Chương trình tập huấn thực hành mổ nội soi ít xâm lấn dành cho bác sĩ nội trú và phẫu thuật viên trẻ.",
    tag: "ĐÀO TẠO CHUYÊN SÂU",
    dateBadge: "Hàng quý",
    location: "Trung tâm Mô phỏng Lâm sàng - Tầng 6",
  },
  {
    id: "toa-dam-tim-mach-can-thiep",
    title: "Tọa Đàm Khoa Học: Cập Nhật Tiến Bộ Tim Mạch Can Thiệp",
    category: "conference",
    categoryLabel: "Tọa Đàm Chuyên Môn",
    imageSrc: "/media/events/toa-dam-tim-mach-can-thiep.jpg",
    imageAlt: "Chuyên gia tim mạch phân tích kết quả điện tâm đồ và can thiệp mạch vành",
    description: "Gặp gỡ và trao đổi chuyên môn sâu về kỹ thuật nong mạch vành, đặt stent thế hệ mới và hồi sức sau can thiệp.",
    tag: "CHUYÊN ĐỀ HỌC THUẬT",
    dateBadge: "Tháng 3",
    location: "Phòng hội thảo chuyên khoa Tim mạch",
  },
  {
    id: "hoi-nghi-ngoai-khoa-quoc-te",
    title: "Hội Nghị Ngoại Khoa Toàn Quốc: Đột Phá Phẫu Thuật Ít Xâm Lấn",
    category: "conference",
    categoryLabel: "Ngoại Khoa",
    imageSrc: "/media/events/hoi-nghi-ngoai-khoa-quoc-te.jpg",
    imageAlt: "Đội ngũ phẫu thuật viên thực hiện ca mổ ứng dụng công nghệ phòng mổ Hybrid",
    description: "Trình diễn các ca phẫu thuật truyền hình trực tiếp với hệ thống cánh tay robot và camera nội soi 4K 3D.",
    tag: "CÔNG NGHỆ CAO",
    dateBadge: "Tháng 8",
    location: "Khu phẫu thuật Hybrid & Hội trường A",
  },
  {
    id: "hoi-thao-chuyen-doi-so-y-te",
    title: "Hội Thảo Quốc Tế: Chuyển Đổi Số & Trí Tuệ Nhân Tạo Trong Y Tế Lâm Sàng",
    category: "conference",
    categoryLabel: "Chuyển Đổi Số",
    imageSrc: "/media/events/hoi-thao-chuyen-doi-so-y-te.jpg",
    imageAlt: "Máy tính bảng hiển thị hồ sơ bệnh án điện tử và hệ thống hỗ trợ ra quyết định lâm sàng",
    description: "Ứng dụng hồ sơ bệnh án điện tử EMR, hỗ trợ chẩn đoán AI và hội chẩn khám bệnh từ xa Telemedicine.",
    tag: "Y TẾ THÔNG MINH",
    dateBadge: "Tháng 9",
    location: "Trung tâm Đổi mới Sáng tạo Y tế",
  },
  {
    id: "hoi-thao-tien-bo-chan-doan-hinh-anh",
    title: "Hội Thảo Khoa Học: Đột Phá Chẩn Đoán Hình Ảnh Với MRI 3.0 Tesla",
    category: "conference",
    categoryLabel: "Chẩn Đoán Hình Ảnh",
    imageSrc: "/media/events/hoi-thao-tien-bo-chan-doan-hinh-anh.jpg",
    imageAlt: "Phòng chụp cộng hưởng từ MRI hiện đại với hệ thống máy 3.0 Tesla",
    description: "Tối ưu hóa phát hiện sớm tổn thương thần kinh sọ não, mạch máu não và các bệnh lý khối u kích thước nhỏ.",
    tag: "CHẨN ĐOÁN TIÊN TIẾN",
    dateBadge: "Tháng 5",
    location: "Phòng Hội thảo Chẩn đoán Hình ảnh",
  },
  {
    id: "toa-dam-y-hoc-co-truyen-ket-hop-hien-dai",
    title: "Tọa Đàm Khoa Học: Kết Hợp Y Học Cổ Truyền Và Y Học Hiện Đại",
    category: "conference",
    categoryLabel: "Y Học Cổ Truyền",
    imageSrc: "/media/events/toa-dam-y-hoc-co-truyen-ket-hop-hien-dai.jpg",
    imageAlt: "Bác sĩ châm cứu bấm huyệt kết hợp phương pháp phục hồi vận động hiện đại",
    description: "Ứng dụng châm cứu, cấy chỉ và thảo dược chuẩn hóa trong điều trị các chứng đau mạn tính và di chứng đột quỵ.",
    tag: "TINH HOA Y HỌC",
    dateBadge: "Tháng 11",
    location: "Khoa Y học Cổ truyền & Phục hồi Chức năng",
  },
  {
    id: "tap-huan-an-toan-su-dung-thuoc-duoc-lam-sang",
    title: "Tập Huấn Toàn Viện: An Toàn Sử Dụng Thuốc & Dược Lâm Sàng",
    category: "conference",
    categoryLabel: "Dược Lâm Sàng",
    imageSrc: "/media/events/tap-huan-an-toan-su-dung-thuoc-duoc-lam-sang.jpg",
    imageAlt: "Dược sĩ lâm sàng kiểm tra đơn thuốc và phân tích nguy cơ tương tác thuốc",
    description: "Giảm thiểu tương tác thuốc bất lợi, tối ưu hóa liều kháng sinh điều trị và xây dựng văn hóa an toàn dùng thuốc.",
    tag: "AN TOÀN DƯỢC",
    dateBadge: "Hàng quý",
    location: "Hội trường B - Tầng 2",
  },
  {
    id: "hoi-thao-nghien-cuu-gen-va-y-hoc-chinh-xac",
    title: "Hội Thảo Quốc Tế: Di Truyền Học & Y Học Chính Xác Cá Thể Hóa",
    category: "conference",
    categoryLabel: "Y Học Phân Tử",
    imageSrc: "/media/events/hoi-thao-nghien-cuu-gen-va-y-hoc-chinh-xac.jpg",
    imageAlt: "Mô hình chuỗi xoắn kép DNA và kỹ thuật giải trình tự gen thế hệ mới",
    description: "Giải trình tự gen thế hệ mới NGS và ứng dụng trong điều trị ung thư trúng đích, liệu pháp miễn dịch cá thể.",
    tag: "Y HỌC TƯƠNG LAI",
    dateBadge: "Tháng 6",
    location: "Viện Nghiên cứu Y Sinh HealthCare",
  },
  {
    id: "hoi-thao-khoa-hoc-nhi-khoa-lam-sang",
    title: "Hội Thảo Khoa Học: Cập Nhật Phác Đồ Điều Trị Nhi Khoa Toàn Diện",
    category: "conference",
    categoryLabel: "Nhi Khoa",
    imageSrc: "/media/events/hoi-thao-khoa-hoc-nhi-khoa-lam-sang.jpg",
    imageAlt: "Bác sĩ và điều dưỡng nhi chăm sóc bệnh nhi tận tình",
    description: "Cập nhật xử trí sốt co giật, viêm phổi cấp, hen phế quản và các bệnh dị ứng miễn dịch phổ biến ở trẻ nhỏ.",
    tag: "BẢO VỆ MẦM NON",
    dateBadge: "Tháng 4",
    location: "Hội trường Khối Nhi - Tầng 3",
  },
  {
    id: "hoi-nghi-khoa-hoc-kiem-soat-nhiem-khuan",
    title: "Hội Nghị Khoa Học Thường Niên: Kiểm Soát Nhiễm Khuẩn Bệnh Viện",
    category: "conference",
    categoryLabel: "Kiểm Soát Nhiễm Khuẩn",
    imageSrc: "/media/events/hoi-nghi-khoa-hoc-kiem-soat-nhiem-khuan.jpg",
    imageAlt: "Hành lang bệnh viện sạch sẽ, khang trang đạt chuẩn vô khuẩn",
    description: "Xây dựng môi trường bệnh viện vô khuẩn, an toàn tối đa cho khu vực phòng phẫu thuật và hồi sức tích cực ICU.",
    tag: "CHUẨN AN TOÀN",
    dateBadge: "Tháng 8",
    location: "Hội trường Grand Hall",
  },
  {
    id: "toa-dam-cham-soc-giam-nhe-cho-benh-nhan-ung-thu",
    title: "Tọa Đàm Y Khoa: Chăm Sóc Giảm Nhẹ & Tâm Lý Cho Người Bệnh Ung Thư",
    category: "conference",
    categoryLabel: "Chăm Sóc Giảm Nhẹ",
    imageSrc: "/media/events/toa-dam-cham-soc-giam-nhe-cho-benh-nhan-ung-thu.jpg",
    imageAlt: "Bác sĩ nắm tay động viên người bệnh trong quá trình điều trị giảm nhẹ",
    description: "Liệu pháp giảm đau đa mô thức, đồng hành nâng đỡ tinh thần và cải thiện chất lượng cuộc sống cho bệnh nhân.",
    tag: "THẤU CẢM & CHIA SẺ",
    dateBadge: "Tháng 10",
    location: "Trung tâm Chăm sóc Giảm nhẹ - Tầng 8",
  },
  {
    id: "hoi-thao-da-lieu-va-tham-my-y-khoa-an-toan",
    title: "Hội Thảo Da Liễu Học: Thẩm Mỹ Y Khoa Chuẩn Y Đức & An Toàn Lâm Sàng",
    category: "conference",
    categoryLabel: "Da Liễu & Thẩm Mỹ",
    imageSrc: "/media/events/hoi-thao-da-lieu-va-tham-my-y-khoa-an-toan.jpg",
    imageAlt: "Chuyên gia da liễu khám soi da và tư vấn liệu trình điều trị phục hồi",
    description: "Cập nhật ứng dụng laser phân đoạn, phục hồi da tổn thương do mỹ phẩm và thẩm mỹ da liễu an toàn chuẩn y khoa.",
    tag: "VẺ ĐẸP KHOA HỌC",
    dateBadge: "Tháng 6",
    location: "Khoa Da Liễu - Thẩm mỹ Da",
  },
  {
    id: "giao-luu-quoc-te-bac-si-noi-tru-asean",
    title: "Diễn Đàn Giao Lưu Y Khoa & Đào Tạo Bác Sĩ Nội Trú Khu Vực ASEAN",
    category: "conference",
    categoryLabel: "Hợp Tác ASEAN",
    imageSrc: "/media/events/giao-luu-quoc-te-bac-si-noi-tru-asean.jpg",
    imageAlt: "Khu vực sảnh hội thảo quốc tế với các đoàn chuyên gia trẻ",
    description: "Kết nối bác sĩ trẻ, trao đổi các ca lâm sàng phức tạp và mở rộng cơ hội học tập, nghiên cứu quốc tế.",
    tag: "HỘI NHẬP QUỐC TẾ",
    dateBadge: "Tháng 12",
    location: "Trung tâm Hội nghị Quốc tế - Tầng 9",
  },
  {
    id: "hoi-nghi-khoa-hoc-duoc-lieu-va-thuoc-moi",
    title: "Hội Thảo Khoa Học: Tiến Bộ Phát Triển Dược Liệu & Thuốc Mới",
    category: "conference",
    categoryLabel: "Dược Học",
    imageSrc: "/media/events/hoi-nghi-khoa-hoc-duoc-lieu-va-thuoc-moi.jpg",
    imageAlt: "Lọ thuốc và chế phẩm dược sinh học đạt chuẩn thực hành tốt sản xuất thuốc GMP",
    description: "Báo cáo thử nghiệm lâm sàng các hoạt chất sinh học mới và chuẩn hóa chiết xuất thảo dược điều trị bệnh mạn tính.",
    tag: "DƯỢC HỌC TIÊN TIẾN",
    dateBadge: "Tháng 5",
    location: "Viện Nghiên cứu Dược lâm sàng",
  },
  {
    id: "toa-dam-tang-huyet-ap-va-suc-khoe-tim-mach",
    title: "Tọa Đàm Khoa Học: Kiểm Soát Huyết Áp Toàn Diện Chuẩn Quốc Tế",
    category: "conference",
    categoryLabel: "Tim Mạch Lâm Sàng",
    imageSrc: "/media/events/toa-dam-tang-huyet-ap-va-suc-khoe-tim-mach.jpg",
    imageAlt: "Thiết bị đo huyết áp điện tử bắp tay chuẩn y tế độ chính xác cao",
    description: "Chiến lược cá thể hóa phác đồ điều trị tăng huyết áp, kiểm soát huyết áp kháng trị và bảo vệ cơ quan đích.",
    tag: "KIỂM SOÁT HUYẾT ÁP",
    dateBadge: "Tháng 4",
    location: "Khoa Tim mạch Can thiệp",
  },
  {
    id: "hoi-nghi-khoa-hoc-hoi-suc-cap-cuu-icu",
    title: "Hội Nghị Khoa Học Thường Niên: Hồi Sức Tích Cực & Chống Độc ICU",
    category: "conference",
    categoryLabel: "Hồi Sức Cấp Cứu",
    imageSrc: "/media/events/hoi-nghi-khoa-hoc-hoi-suc-cap-cuu-icu.jpg",
    imageAlt: "Khu giường bệnh hồi sức tích cực ICU trang bị máy thở và monitor theo dõi liên tục",
    description: "Cập nhật chiến lược thở máy bảo vệ phổi ARDS, lọc máu liên tục CRRT và kiểm soát sốc nhiễm khuẩn nặng.",
    tag: "HỒI SỨC TÍCH CỰC",
    dateBadge: "Tháng 7",
    location: "Khu Hồi sức Tích cực & Hội trường A",
  },
  {
    id: "hoi-thao-dot-pha-tri-lieu-te-bao-goc",
    title: "Hội Thảo Khoa Học: Ứng Dụng Liệu Pháp Tế Bào Gốc Trong Y Học",
    category: "conference",
    categoryLabel: "Y Học Tái Tạo",
    imageSrc: "/media/events/hoi-thao-dot-pha-tri-lieu-te-bao-goc.jpg",
    imageAlt: "Các ống nghiệm nuôi cấy và bảo quản tế bào gốc trong môi trường nitơ lỏng",
    description: "Báo cáo đột phá ứng dụng tế bào gốc trung mô trong điều trị thoái hóa khớp gối, tổn thương tủy sống và xơ gan.",
    tag: "Y HỌC TÁI TẠO",
    dateBadge: "Tháng 8",
    location: "Trung tâm Y học Tái tạo & Trị liệu Tế bào",
  },
  {
    id: "hoi-thao-phong-ngua-tai-bien-mach-mau-nao",
    title: "Hội Thảo Chuyên Đề: Dự Phòng Thứ Phát Đột Quỵ & Phình Mạch Não",
    category: "conference",
    categoryLabel: "Thần Kinh Mạch Máu",
    imageSrc: "/media/events/hoi-thao-phong-ngua-tai-bien-mach-mau-nao.jpg",
    imageAlt: "Phim chụp cộng hưởng từ mạch máu não MRA phát hiện sớm phình động mạch",
    description: "Kỹ thuật can thiệp nội mạch nút phình động mạch não bằng coil và stent chuyển dòng giúp ngăn ngừa xuất huyết tái phát.",
    tag: "ĐỘT PHÁ THẦN KINH",
    dateBadge: "Tháng 9",
    location: "Trung tâm Đột quỵ & Can thiệp Thần kinh",
  },
  {
    id: "hoi-thao-y-hoc-the-thao-va-chan-thuong",
    title: "Hội Thảo Y Học Thể Thao: Tái Tạo Dây Chằng & Chấn Thương Vận Động",
    category: "conference",
    categoryLabel: "Y Học Thể Thao",
    imageSrc: "/media/events/hoi-thao-y-hoc-the-thao-va-chan-thuong.jpg",
    imageAlt: "Phim X-quang khớp gối đánh giá tổn thương dây chằng chéo trước và sụn chêm",
    description: "Ứng dụng phẫu thuật nội soi khớp gối ít xâm lấn và phác đồ phục hồi thể lực giúp vận động viên sớm quay lại thi đấu.",
    tag: "Y HỌC THỂ THAO",
    dateBadge: "Tháng 10",
    location: "Khoa Phẫu thuật Khớp & Y học Thể thao",
  },

  // ==========================================
  // 2. Khám sức khỏe cộng đồng & Hoạt động Thiện nguyện
  // ==========================================
  {
    id: "kham-benh-tu-thien-cong-dong",
    title: "Chương Trình Khám Sức Khỏe Từ Thiện & Chăm Sóc Sức Khỏe Cộng Đồng",
    category: "charity",
    categoryLabel: "Khám Từ Thiện",
    imageSrc: "/media/events/kham-benh-tu-thien-cong-dong.jpg",
    imageAlt: "Đoàn y bác sĩ HealthCare đo huyết áp và khám bệnh cho người dân tại trung tâm y tế cộng đồng",
    description: "Đoàn công tác y bác sĩ tình nguyện thăm khám, phát thuốc miễn phí và tư vấn sức khỏe cho bà con vùng khó khăn.",
    tag: "THIỆN NGUYỆN",
    dateBadge: "Định kỳ hàng tháng",
    location: "Các xã vùng sâu, vùng xa & vùng khó khăn",
  },
  {
    id: "kham-tam-soat-nguoi-cao-tuoi",
    title: "Ngày Hội Sức Khỏe Vàng: Tầm Soát Miễn Phí Cho Người Cao Tuổi",
    category: "charity",
    categoryLabel: "Chăm Sóc Người Cao Tuổi",
    imageSrc: "/media/events/kham-tam-soat-nguoi-cao-tuoi.jpg",
    imageAlt: "Bác sĩ tận tình tư vấn kết quả khám sức khỏe cho cụ bà",
    description: "Khám tổng quát, đo mật độ xương, xét nghiệm đường huyết và tư vấn phòng ngừa té ngã cho người từ 60 tuổi.",
    tag: "TRI ÂN NGƯỜI CAO TUỔI",
    dateBadge: "Tháng 10",
    location: "Sảnh đón tiếp & Trung tâm Khám theo yêu cầu",
  },
  {
    id: "ngay-hoi-mat-sang-hoc-duong",
    title: "Chương Trình 'Mắt Sáng Tương Lai': Khám Thị Lực Học Đường",
    category: "charity",
    categoryLabel: "Y Tế Học Đường",
    imageSrc: "/media/events/ngay-hoi-mat-sang-hoc-duong.jpg",
    imageAlt: "Bác sĩ mắt kiểm tra thị lực bằng máy đo khúc xạ tự động cho học sinh",
    description: "Tầm soát tật khúc xạ cận thị, loạn thị học đường, tư vấn tư thế ngồi chuẩn và trao tặng kính thuốc miễn phí.",
    tag: "VÌ NỤ CƯỜI TRẺ THƠ",
    dateBadge: "Đầu năm học",
    location: "Các trường tiểu học & THCS địa bàn",
  },
  {
    id: "tu-van-dinh-duong-hoc-duong",
    title: "Hội Thảo Dinh Dưỡng: Phát Triển Thể Chất & Chiều Cao Trẻ Em",
    category: "charity",
    categoryLabel: "Dinh Dưỡng Nhi",
    imageSrc: "/media/events/tu-van-dinh-duong-hoc-duong.jpg",
    imageAlt: "Bác sĩ dinh dưỡng tư vấn thực đơn khoa học cho mẹ và bé",
    description: "Hướng dẫn thực đơn khoa học, bổ sung vi chất hợp lý và theo dõi biểu đồ tăng trưởng chuẩn WHO cho trẻ nhỏ.",
    tag: "CẨM NANG GIA ĐÌNH",
    dateBadge: "Tháng 6",
    location: "Khoa Khám Nhi & Dinh dưỡng Lâm sàng",
  },
  {
    id: "tam-soat-ung-thu-cong-dong",
    title: "Chương Trình Tầm Soát Ung Thư Sớm: Thấu Hiểu Cơ Thể - Đón Đầu Sức Khỏe",
    category: "charity",
    categoryLabel: "Tầm Soát Ung Thư",
    imageSrc: "/media/events/tam-soat-ung-thu-cong-dong.jpg",
    imageAlt: "Bác sĩ ung bướu tư vấn kết quả tầm soát và giải thích phác đồ phòng bệnh",
    description: "Tầm soát ung thư tiêu hóa, phổi, gan và tuyến giáp với gói xét nghiệm sinh học phân tử hiện đại.",
    tag: "PHÒNG BỆNH CHỦ ĐỘNG",
    dateBadge: "Thường xuyên",
    location: "Trung tâm Ung Bướu & Y học Hạt nhân",
  },
  {
    id: "chuong-trinh-trao-qua-benh-nhi",
    title: "Chương Trình 'Trao Gửi Yêu Thương': Tặng Quà Cho Bệnh Nhi Nội Trú",
    category: "charity",
    categoryLabel: "Công Tác Xã Hội",
    imageSrc: "/media/events/chuong-trinh-trao-qua-benh-nhi.jpg",
    imageAlt: "Bác sĩ nhi khoa và mẹ động viên nụ cười rạng rỡ của bé gái đang điều trị",
    description: "Mang đến niềm vui, đồ chơi, sách truyện và những phần quà ấm áp giúp các bé có thêm động lực hồi phục.",
    tag: "VÒNG TAY NHÂN ÁI",
    dateBadge: "Tết & Trung thu",
    location: "Khoa Nội trú Nhi - Tầng 4",
  },
  {
    id: "ngay-hoi-cham-soc-suc-khoe-phu-nu",
    title: "Ngày Hội Phái Đẹp Tỏa Sáng: Tầm Soát Ung Thư Vú & Cổ Tử Cung",
    category: "charity",
    categoryLabel: "Sức Khỏe Phụ Nữ",
    imageSrc: "/media/events/ngay-hoi-cham-soc-suc-khoe-phu-nu.jpg",
    imageAlt: "Bác sĩ sản phụ khoa tư vấn sức khỏe phụ nữ tận tâm",
    description: "Miễn phí siêu âm tuyến vú, xét nghiệm Pap smear và tư vấn sức khỏe sinh sản, tiền mãn kinh cho phụ nữ.",
    tag: "VÌ NỬA THẾ GIỚI",
    dateBadge: "20 tháng 10",
    location: "Khoa Phụ Sản & Trung tâm Chẩn đoán Hình ảnh",
  },
  {
    id: "ngay-hoi-nu-cuoi-hoc-duong",
    title: "Ngày Hội Nha Khoa Học Đường: Nụ Cười Xinh - Tương Lai Sáng",
    category: "charity",
    categoryLabel: "Nha Khoa Học Đường",
    imageSrc: "/media/events/ngay-hoi-nu-cuoi-hoc-duong.jpg",
    imageAlt: "Bác sĩ nha khoa khám và hướng dẫn chải răng đúng cách cho thiếu nhi",
    description: "Khám răng miễn phí, bôi vecni fluor phòng ngừa sâu răng và hướng dẫn kỹ năng chăm sóc răng miệng học đường.",
    tag: "NỤ CƯỜI TƯƠNG LAI",
    dateBadge: "Tháng 3",
    location: "Khu khám Răng Hàm Mặt Nhi",
  },
  {
    id: "chien-dich-tam-soat-gan-mat-tieu-hoa",
    title: "Chiến Dịch Tầm Soát: Vì Một Lá Gan Khỏe - Tiêu Hóa An Lành",
    category: "charity",
    categoryLabel: "Tiêu Hóa Gan Mật",
    imageSrc: "/media/events/chien-dich-tam-soat-gan-mat-tieu-hoa.jpg",
    imageAlt: "Hệ thống nội soi tiêu hóa ống mềm hiện đại tầm soát tổn thương sớm",
    description: "Xét nghiệm men gan, sàng lọc viêm gan virus B/C và tầm soát polyp đường tiêu hóa bằng nội soi không đau.",
    tag: "TIÊU HÓA AN TÂM",
    dateBadge: "Tháng 7",
    location: "Trung tâm Nội soi Tiêu hóa & Gan mật",
  },
  {
    id: "kham-sang-loc-benh-ly-tuyen-giap",
    title: "Chương Trình Khám Tầm Soát Bệnh Lý Tuyến Giáp & Rối Loạn Nội Tiết",
    category: "charity",
    categoryLabel: "Nội Tiết Tuyến Giáp",
    imageSrc: "/media/events/kham-sang-loc-benh-ly-tuyen-giap.jpg",
    imageAlt: "Kỹ thuật viên phòng xét nghiệm phân tích mẫu sinh hóa nội tiết",
    description: "Siêu âm tuyến giáp Doppler màu và xét nghiệm định lượng hormone TSH giúp phát hiện sớm u nang và bướu cổ.",
    tag: "NỘI TIẾT KHỎE",
    dateBadge: "Tháng 5",
    location: "Khoa Nội tiết & Đái tháo đường",
  },
  {
    id: "ngay-hoi-tu-van-suc-khoe-tien-hon-nhan",
    title: "Ngày Hội Tư Vấn Sức Khỏe Tiền Hôn Nhân & Sàng Lọc Di Truyền",
    category: "charity",
    categoryLabel: "Sức Khỏe Sinh Sản",
    imageSrc: "/media/events/ngay-hoi-tu-van-suc-khoe-tien-hon-nhan.jpg",
    imageAlt: "Bác sĩ chuyên khoa sản và di truyền tư vấn tiền hôn nhân cho các cặp đôi",
    description: "Khám sức khỏe tiền hôn nhân, xét nghiệm gen Thalassemia và tư vấn tiêm phòng vắc-xin chuẩn bị mang thai an toàn.",
    tag: "HẠNH PHÚC GIA ĐINH",
    dateBadge: "Tháng 2",
    location: "Trung tâm Hỗ trợ Sinh sản & Di truyền",
  },
  {
    id: "kham-sang-loc-benh-ly-tai-mui-hong-hoc-duong",
    title: "Chương Trình Khám Tầm Soát Tai Mũi Họng Cho Trẻ Mầm Non",
    category: "charity",
    categoryLabel: "Tai Mũi Họng Nhi",
    imageSrc: "/media/events/kham-sang-loc-benh-ly-tai-mui-hong-hoc-duong.jpg",
    imageAlt: "Bác sĩ tai mũi họng nội soi nhẹ nhàng kiểm tra vòm họng cho trẻ nhỏ",
    description: "Khám nội soi tai mũi họng miễn phí, phát hiện sớm viêm VA phì đại, viêm amidan và viêm tai giữa ứ dịch ở trẻ em.",
    tag: "TAI MŨI HỌNG NHI",
    dateBadge: "Tháng 9",
    location: "Khoa Tai Mũi Họng Nhi",
  },
  {
    id: "chien-dich-tam-soat-ung-thu-da",
    title: "Chiến Dịch Tầm Soát Nốt Ruồi & Phát Hiện Sớm Ung Thư Da",
    category: "charity",
    categoryLabel: "Da Liễu Ung Bướu",
    imageSrc: "/media/events/chien-dich-tam-soat-ung-thu-da.jpg",
    imageAlt: "Bác sĩ da liễu sử dụng kính Dermoscopy phóng đại soi nốt ruồi nghi ngờ",
    description: "Tầm soát nốt ruồi bất thường, nốt đen biến đổi hình dạng nhằm phát hiện sớm u hắc tố Melanoma ngay giai đoạn đầu.",
    tag: "LÀN DA KHỎE ĐẸP",
    dateBadge: "Tháng 5",
    location: "Phòng khám Da liễu Chuyên sâu",
  },
  {
    id: "toa-dam-giai-phap-dinh-duong-cho-tre-bieng-an",
    title: "Tọa Đàm Y Khoa: Giải Pháp Khoa Học Cho Trẻ Biếng Ăn & Chậm Tăng Cân",
    category: "charity",
    categoryLabel: "Dinh Dưỡng Nhi",
    imageSrc: "/media/events/toa-dam-giai-phap-dinh-duong-cho-tre-bieng-an.jpg",
    imageAlt: "Bác sĩ dinh dưỡng hướng dẫn phụ huynh cách phối hợp thực phẩm giàu kẽm và vi chất",
    description: "Chia sẻ kinh nghiệm xây dựng thực đơn đa dạng, bổ sung men vi sinh và kẽm sinh học giúp bé ăn ngon tự nhiên.",
    tag: "BÉ KHỎE MẸ AN TÂM",
    dateBadge: "Tháng 8",
    location: "Khoa Dinh dưỡng Tiết chế",
  },
  {
    id: "ngay-hoi-cham-soc-mat-cho-nguoi-cao-tuoi",
    title: "Ngày Hội Mắt Sáng Tuổi Vàng: Tầm Soát Đục Thủy Tinh Thể & Cườm",
    category: "charity",
    categoryLabel: "Mắt Lão Khoa",
    imageSrc: "/media/events/ngay-hoi-cham-soc-mat-cho-nguoi-cao-tuoi.jpg",
    imageAlt: "Bác sĩ mắt khám sinh hiển vi đáy mắt cho bệnh nhân cao tuổi",
    description: "Khám mắt miễn phí, đo nhãn áp tầm soát cườm nước Glaucoma và tư vấn phẫu thuật Phaco thay thủy tinh thể hiện đại.",
    tag: "MẮT SÁNG TUỔI VÀNG",
    dateBadge: "Tháng 10",
    location: "Khoa Mắt & Phẫu thuật Khúc xạ",
  },

  // ==========================================
  // 3. Hiến máu tình nguyện & Ngân hàng máu
  // ==========================================
  {
    id: "ngay-hoi-hien-mau-nhan-dao",
    title: "Ngày Hội Hiến Máu Tình Nguyện 'Hành Trình Đỏ - Trao Hy Vọng, Nhận Nụ Cười'",
    category: "blood_donation",
    categoryLabel: "Hiến Máu Nhân Đạo",
    imageSrc: "/media/events/ngay-hoi-hien-mau-nhan-dao.jpg",
    imageAlt: "Tình nguyện viên và điều dưỡng tươi cười trong buổi hiến máu tình nguyện tại sảnh bệnh viện",
    description: "Hàng trăm đơn vị máu quý giá được tiếp nhận để phục vụ cấp cứu và điều trị cho các bệnh nhân hiểm nghèo.",
    tag: "NGHĨA CỬ CAO ĐẸP",
    dateBadge: "Tháng 7",
    location: "Sảnh chính Tòa nhà Trung tâm",
  },
  {
    id: "ngay-hoi-hien-mau-giot-hong-blouse-trang",
    title: "Ngày Hội Hiến Máu: Giọt Hồng Blouse Trắng - Thắp Sáng Hy Vọng",
    category: "blood_donation",
    categoryLabel: "Hiến Máu Áo Trắng",
    imageSrc: "/media/events/ngay-hoi-hien-mau-giot-hong-blouse-trang.jpg",
    imageAlt: "Các ống nghiệm mẫu máu được bảo quản tiêu chuẩn an toàn truyền máu",
    description: "Đội ngũ thầy thuốc xung kích sẻ chia những giọt máu đào quý giá tiếp sức cứu sống người bệnh trong cơn nguy kịch.",
    tag: "TRÁCH NHIỆM ÁO TRẮNG",
    dateBadge: "Tháng 1",
    location: "Trung tâm Huyết học - Truyền máu",
  },

  // ==========================================
  // 4. Lễ kỷ niệm, Cột mốc & Hợp tác quốc tế
  // ==========================================
  {
    id: "ky-niem-ngay-thay-thuoc-viet-nam",
    title: "Lễ Kỷ Niệm Ngày Thầy Thuốc Việt Nam 27/2: Tri Ân & Vinh Danh Lực Lượng Y Tế",
    category: "anniversary",
    categoryLabel: "Lễ Kỷ Niệm",
    imageSrc: "/media/events/ky-niem-ngay-thay-thuoc-viet-nam.jpg",
    imageAlt: "Đoàn đại biểu lãnh đạo bệnh viện và y bác sĩ nhận hoa và bằng khen trên sân khấu trang trọng",
    description: "Tôn vinh sự cống hiến thầm lặng của các y bác sĩ, điều dưỡng và cán bộ nhân viên y tế vì sức khỏe người bệnh.",
    tag: "TRI ÂN THẦY THUỐC",
    dateBadge: "27 tháng 2",
    location: "Trung tâm Hội nghị Bệnh viện HealthCare",
  },
  {
    id: "khanh-thanh-trung-tam-ky-thuat-cao",
    title: "Lễ Khánh Thành Tòa Nhà Khám Chữa Bệnh Kỹ Thuật Cao Mới",
    category: "anniversary",
    categoryLabel: "Khánh Thành",
    imageSrc: "/media/events/khanh-thanh-trung-tam-ky-thuat-cao.jpg",
    imageAlt: "Mặt tiền tòa nhà bệnh viện kỹ thuật cao khang trang hiện đại trong ngày khánh thành",
    description: "Đưa vào vận hành khối nhà 500 giường bệnh đạt tiêu chuẩn quốc tế, trang bị máy chụp MRI 3.0T và CT 512 lát cắt.",
    tag: "BƯỚC NGOẶT PHÁT TRIỂN",
    dateBadge: "Cột mốc 2026",
    location: "Cơ sở trung tâm - Số 1 Đại lộ Y Học",
  },
  {
    id: "le-ky-ket-hop-tac-y-khoa-quoc-te",
    title: "Lễ Ký Kết Hợp Tác Y Khoa Chiến Lược & Chuyển Giao Công Nghệ",
    category: "anniversary",
    categoryLabel: "Hợp Tác Quốc Tế",
    imageSrc: "/media/events/le-ky-ket-hop-tac-y-khoa-quoc-te.jpg",
    imageAlt: "Hành lang hội đàm quốc tế giữa các đoàn chuyên gia y tế",
    description: "Ký kết thỏa thuận hợp tác đào tạo và hỗ trợ hội chẩn trực tuyến từ xa với các trung tâm y khoa hàng đầu khu vực.",
    tag: "HỘI NHẬP TOÀN CẦU",
    dateBadge: "Định kỳ",
    location: "Phòng Khánh tiết Ngoại giao - Tầng 9",
  },
  {
    id: "don-nhan-chung-nhan-chat-luong-jci",
    title: "Lễ Đón Nhận Chứng Chỉ Quản Lý Chất Lượng Y Tế Quốc Tế",
    category: "anniversary",
    categoryLabel: "Chứng Nhận Quốc Tế",
    imageSrc: "/media/events/don-nhan-chung-nhan-chat-luong-jci.jpg",
    imageAlt: "Khu vực sảnh đón tiếp bệnh viện đạt chuẩn chất lượng quốc tế",
    description: "Khẳng định cam kết kiên định về an toàn người bệnh, kiểm soát nhiễm khuẩn và chất lượng dịch vụ chuẩn mực.",
    tag: "CHUẨN MỰC QUỐC TẾ",
    dateBadge: "Cột mốc vàng",
    location: "Toàn hệ thống bệnh viện",
  },
  {
    id: "le-trao-hoc-bong-y-khoa-tai-nang-tre",
    title: "Lễ Trao Học Bổng Y Khoa: Ươm Mầm Tài Năng Thầy Thuốc Tương Lai",
    category: "anniversary",
    categoryLabel: "Học Bổng Y Khoa",
    imageSrc: "/media/events/le-trao-hoc-bong-y-khoa-tai-nang-tre.jpg",
    imageAlt: "Tòa nhà Trung tâm Đào tạo và Viện Nghiên cứu Tim mạch HealthCare",
    description: "Trao tặng 50 suất học bổng toàn phần nhằm bồi dưỡng và đồng hành cùng các sinh viên y khoa và bác sĩ nội trú xuất sắc.",
    tag: "ƯƠM MẦM TÀI NĂNG",
    dateBadge: "Tháng 9",
    location: "Hội trường Viện Đào tạo Y khoa",
  },
  {
    id: "le-ra-mat-tong-dai-cap-cuu-115-thong-minh",
    title: "Lễ Ra Mắt Hệ Thống Điều Phối Cấp Cứu Ngoại Viện Thông Minh 24/7",
    category: "anniversary",
    categoryLabel: "Cấp Cứu Ngoại Viện",
    imageSrc: "/media/events/le-ra-mat-tong-dai-cap-cuu-115-thong-minh.jpg",
    imageAlt: "Khu phức hợp Trung tâm Can thiệp Cấp cứu Thần kinh & Đột quỵ",
    description: "Tích hợp bản đồ số định vị xe cứu thương thời gian thực, liên thông dữ liệu sinh tồn tiền viện cứu sống giờ vàng.",
    tag: "GIỜ VÀNG CỨU SỐNG",
    dateBadge: "Quý 1/2026",
    location: "Trung tâm Cấp cứu 115 & Đột quỵ",
  },
  {
    id: "khanh-thanh-co-so-moi-trung-tam-kham-theo-yeu-cau",
    title: "Lễ Khánh Thành Phân Hiệu Mới: Trung Tâm Khám & Điều Trị Kỹ Thuật Cao",
    category: "anniversary",
    categoryLabel: "Mở Rộng Mạng Lưới",
    imageSrc: "/media/events/khanh-thanh-co-so-moi-trung-tam-kham-theo-yeu-cau.jpg",
    imageAlt: "Phân hiệu bệnh viện mới khang trang trên khuôn viên xanh rộng lớn",
    description: "Gia tăng năng lực phục vụ hơn 3.000 lượt người bệnh ngoại trú mỗi ngày với hạ tầng tiện nghi và quy trình khép kín.",
    tag: "PHÁT TRIỂN MẠNG LƯỚI",
    dateBadge: "Cột mốc mới",
    location: "Cơ sở Phía Tây - Đại lộ Hòa Bình",
  },
  {
    id: "le-ky-niem-thanh-lap-vien-tim-mach",
    title: "Lễ Kỷ Niệm 15 Năm Thành Lập Viện Tim Mạch Bệnh Viện HealthCare",
    category: "anniversary",
    categoryLabel: "Kỷ Niệm Viện",
    imageSrc: "/media/events/le-ky-niem-thanh-lap-vien-tim-mach.jpg",
    imageAlt: "Tòa nhà Viện Tim mạch với trang thiết bị phòng thông tim Catheterization Lab hiện đại",
    description: "Chặng đường can thiệp cứu sống hơn 30.000 trái tim, đào tạo hàng trăm bác sĩ tim mạch can thiệp cho tuyến dưới.",
    tag: "15 NĂM CỐNG HIẾN",
    dateBadge: "Tháng 8",
    location: "Hội trường Lớn Viện Tim mạch",
  },
  {
    id: "le-khanh-thanh-khu-phuc-hop-nhi-khoa-quoc-te",
    title: "Lễ Khánh Thành Khu Phức Hợp Điều Trị Nhi Khoa Tiêu Chuẩn Quốc Tế",
    category: "anniversary",
    categoryLabel: "Khánh Thành Khối Nhi",
    imageSrc: "/media/events/le-khanh-thanh-khu-phuc-hop-nhi-khoa-quoc-te.jpg",
    imageAlt: "Khuôn viên sảnh tòa nhà Nhi khoa với thiết kế thân thiện, ấm cúng và đầy màu sắc",
    description: "Khối nhà 200 giường điều trị nhi khoa khép kín, khu vui chơi hồi phục giúp các bé vượt qua sợ hãi khi khám bệnh.",
    tag: "THẾ GIỚI CỦA BÉ",
    dateBadge: "Tháng 6",
    location: "Khu Phức hợp Khối Nhi Mới",
  },

  // ==========================================
  // 5. Chiến dịch y tế dự phòng & Phong trào sức khỏe
  // ==========================================
  {
    id: "tuan-le-phong-chong-dot-quy",
    title: "Tuần Lễ Truyền Thông: Nhận Diện & Xử Trí Đột Quỵ Sớm FAST",
    category: "public_health",
    categoryLabel: "Truyền Thông Y Tế",
    imageSrc: "/media/events/tuan-le-phong-chong-dot-quy.jpg",
    imageAlt: "Hình ảnh mô phỏng não bộ và thông điệp nhận diện dấu hiệu đột quỵ FAST",
    description: "Nâng cao nhận thức cộng đồng về giờ vàng cấp cứu đột quỵ (4.5 giờ đầu) để cứu sống chức năng thần kinh.",
    tag: "CẤP CỨU ĐỘT QUỴ",
    dateBadge: "Tháng 10",
    location: "Hệ thống màn hình thông tin & Fanpage chính thức",
  },
  {
    id: "dien-tap-cap-cuu-tham-hoa",
    title: "Diễn Tập Cấp Cứu Thảm Họa & Xử Trí Chấn Thương Hàng Loạt",
    category: "public_health",
    categoryLabel: "Diễn Tập Cấp Cứu",
    imageSrc: "/media/events/dien-tap-cap-cuu-tham-hoa.jpg",
    imageAlt: "Xe cứu thương và đội ngũ y bác sĩ cấp cứu sẵn sàng ứng trực",
    description: "Kích hoạt quy trình Báo Động Đỏ nội viện (Code Red), diễn tập phối hợp liên khoa xử trí chấn thương cấp cứu hàng loạt.",
    tag: "BÁO ĐỘNG ĐỎ",
    dateBadge: "Tháng 4",
    location: "Khu vực Cấp cứu & Bãi đáp trực thăng",
  },
  {
    id: "chien-dich-tiem-chung-mua-dong-xuan",
    title: "Chiến Dịch Tiêm Chủng Mở Rộng: Bảo Vệ Cả Gia Đình Mùa Đông Xuân",
    category: "public_health",
    categoryLabel: "Tiêm Chủng Vaccine",
    imageSrc: "/media/events/chien-dich-tiem-chung-mua-dong-xuan.jpg",
    imageAlt: "Nhân viên y tế tiêm vaccine phòng cúm an toàn cho người bệnh",
    description: "Chương trình trợ giá tiêm chủng vắc xin cúm, phế cầu, viêm não Nhật Bản và sởi - quai bị - rubella.",
    tag: "LÁ CHẮN SỨC KHỎE",
    dateBadge: "Tháng 11 - Tháng 2",
    location: "Trung tâm Tiêm chủng Vaccine HealthCare",
  },
  {
    id: "phat-dong-phong-trao-ve-sinh-tay",
    title: "Lễ Phát Động Phong Trào: Vệ Sinh Tay Bệnh Viện Vì An Toàn Người Bệnh",
    category: "public_health",
    categoryLabel: "An Toàn Người Bệnh",
    imageSrc: "/media/events/phat-dong-phong-trao-ve-sinh-tay.jpg",
    imageAlt: "Nhân viên y tế đeo găng tay vô khuẩn sẵn sàng thực hiện thủ thuật",
    description: "Tất cả cán bộ y tế đồng lòng cam kết tuân thủ nghiêm ngặt 5 thời điểm rửa tay để đẩy lùi nhiễm khuẩn bệnh viện.",
    tag: "BẢO VỆ NGƯỜI BỆNH",
    dateBadge: "5 tháng 5",
    location: "Các khoa phòng lâm sàng toàn viện",
  },
  {
    id: "ngay-hoi-di-bo-vi-trai-tim-khoe",
    title: "Ngày Hội Đi Bộ Đồng Hành: Vận Động Vì Một Trái Tim Khỏe Mạnh",
    category: "public_health",
    categoryLabel: "Vận Động Sức Khỏe",
    imageSrc: "/media/events/ngay-hoi-di-bo-vi-trai-tim-khoe.jpg",
    imageAlt: "Vận động viên tham gia chạy bộ rèn luyện sức bền tim mạch",
    description: "Hưởng ứng Ngày Tim mạch Thế giới, lan tỏa thông điệp 10.000 bước chân mỗi ngày đẩy lùi xơ vữa động mạch.",
    tag: "TRÁI TIM KHỎE",
    dateBadge: "29 tháng 9",
    location: "Công viên trung tâm & Cung đường chạy HealthCare",
  },
  {
    id: "sinh-hoat-clb-benh-nhan-tieu-duong",
    title: "Sinh Hoạt Định Kỳ CLB Đái Tháo Đường & Tăng Huyết Áp",
    category: "public_health",
    categoryLabel: "Câu Lạc Bộ Bệnh Nhân",
    imageSrc: "/media/events/sinh-hoat-clb-benh-nhan-tieu-duong.jpg",
    imageAlt: "Bác sĩ hướng dẫn người bệnh cách đọc chỉ số đường huyết mao mạch",
    description: "Diễn đàn chia sẻ kinh nghiệm sống vui, sống khỏe, chế độ dinh dưỡng và theo dõi đường huyết tại nhà.",
    tag: "ĐỒNG HÀNH BỆNH NHÂN",
    dateBadge: "Thứ 7 tuần thứ 2 hàng tháng",
    location: "Hội trường Bệnh viện - Tầng 3",
  },
  {
    id: "lop-hoc-tien-san-hanh-trinh-lam-me.jpg",
    title: "Lớp Học Tiền Sản Miễn Phí: Hành Trình Làm Mẹ An Nhiên",
    category: "public_health",
    categoryLabel: "Lớp Học Tiền Sản",
    imageSrc: "/media/events/lop-hoc-tien-san-hanh-trinh-lam-me.jpg",
    imageAlt: "Bác sĩ sản khoa siêu âm định kỳ theo dõi sự phát triển của thai nhi",
    description: "Bác sĩ sản phụ khoa và nữ hộ sinh hướng dẫn kỹ năng thở giảm đau, tư thế chuyển dạ và chăm sóc trẻ sơ sinh an toàn.",
    tag: "ĐỒNG HÀNH VƯỢT CẠN",
    dateBadge: "Thứ 7 hàng tuần",
    location: "Hội trường Khoa Sản - Tầng 5",
  },
  {
    id: "ngay-hoi-hoi-sinh-van-dong",
    title: "Ngày Hội Phục Hồi Chức Năng: Hồi Sinh Vận Động Sau Bệnh Lý",
    category: "public_health",
    categoryLabel: "Phục Hồi Chức Năng",
    imageSrc: "/media/events/ngay-hoi-hoi-sinh-van-dong.jpg",
    imageAlt: "Kỹ thuật viên vật lý trị liệu hỗ trợ bệnh nhân tập vận động khớp gối",
    description: "Phương pháp vật lý trị liệu hiện đại giúp người bệnh phục hồi chức năng vận động sau chấn thương và phẫu thuật.",
    tag: "BƯỚC ĐI TỰ LẬP",
    dateBadge: "Tháng 9",
    location: "Trung tâm Vật lý Trị liệu & Phục hồi Chức năng",
  },
  {
    id: "kham-sang-loc-benh-ly-ho-hap",
    title: "Chiến Dịch Tầm Soát: Lá Phổi Khỏe Mạnh - Đẩy Lùi Hen & COPD",
    category: "public_health",
    categoryLabel: "Bệnh Lý Hô Hấp",
    imageSrc: "/media/events/kham-sang-loc-benh-ly-ho-hap.jpg",
    imageAlt: "Hình ảnh cấu trúc đường dẫn khí và nhu mô phổi khỏe mạnh",
    description: "Đo chức năng thông khí phổi miễn phí, tầm soát hen phế quản và bệnh phổi tắc nghẽn mạn tính cho người có nguy cơ.",
    tag: "LÁ PHỔI KHỎE MẠNH",
    dateBadge: "Tháng 11",
    location: "Phòng khám Hô hấp & Dị ứng Miễn dịch",
  },
  {
    id: "tuan-le-nang-cao-nhan-thuc-loang-xuong",
    title: "Tuần Lễ Sức Khỏe Xương Khớp: Phòng Ngừa Loãng Xương & Thoái Hóa",
    category: "public_health",
    categoryLabel: "Cơ Xương Khớp",
    imageSrc: "/media/events/tuan-le-nang-cao-nhan-thuc-loang-xuong.jpg",
    imageAlt: "Phim chụp X-quang khớp gối và cột sống đánh giá mật độ xương",
    description: "Đo mật độ xương DXA tiêu chuẩn vàng, tư vấn bổ sung canxi D3 và bài tập vận động phòng ngừa thoái hóa sớm.",
    tag: "KHUNG XƯƠNG KHỎE",
    dateBadge: "20 tháng 10",
    location: "Khoa Cơ Xương Khớp",
  },
  {
    id: "ngay-hoi-suc-khoe-tam-than-va-giam-stress",
    title: "Ngày Hội Sức Khỏe Tâm Trí: Cân Bằng Thân - Tâm - Trí Thời Hiện Đại",
    category: "public_health",
    categoryLabel: "Sức Khỏe Tâm Trí",
    imageSrc: "/media/events/ngay-hoi-suc-khoe-tam-than-va-giam-stress.jpg",
    imageAlt: "Không gian tĩnh tâm thư thái giúp giải tỏa căng thẳng lo âu",
    description: "Tham vấn tâm lý cá nhân miễn phí, hướng dẫn kỹ thuật thở xả stress và rèn luyện chánh niệm trong cuộc sống bận rộn.",
    tag: "BÌNH YÊN TÂM TRÍ",
    dateBadge: "10 tháng 10",
    location: "Trung tâm Tâm lý Lâm sàng & Sức khỏe Tâm thần",
  },
  {
    id: "chuong-trinh-kham-suc-khoe-nam-khoa-dinh-ky",
    title: "Chương Trình Chăm Sóc Sức Khỏe Nam Giới: Bản Lĩnh Phái Mạnh",
    category: "public_health",
    categoryLabel: "Sức Khỏe Nam Giới",
    imageSrc: "/media/events/chuong-trinh-kham-suc-khoe-nam-khoa-dinh-ky.jpg",
    imageAlt: "Bác sĩ nam học tư vấn chuyên sâu về sức khỏe sinh sản nam giới",
    description: "Tầm soát u xơ tiền liệt tuyến, rối loạn chuyển hóa và sàng lọc các bệnh lý đường tiết niệu nam giới độ tuổi trung niên.",
    tag: "BẢN LĨNH PHÁI MẠNH",
    dateBadge: "Tháng 11",
    location: "Trung tâm Nam học & Tiết niệu",
  },
  {
    id: "ngay-hoi-dinh-duong-hoc-va-an-toan-thuc-pham",
    title: "Ngày Hội Dinh Dưỡng: Bữa Ăn Lành Mạnh - Cuộc Sống Trường Thọ",
    category: "public_health",
    categoryLabel: "Dinh Dưỡng Lâm Sàng",
    imageSrc: "/media/events/ngay-hoi-dinh-duong-hoc-va-an-toan-thuc-pham.jpg",
    imageAlt: "Rau củ quả tươi sạch đại diện cho thực đơn dinh dưỡng khoa học",
    description: "Tư vấn chế độ ăn Địa Trung Hải, thực đơn giảm muối bảo vệ tim mạch và chế độ kiêng khem chuẩn cho bệnh mạn tính.",
    tag: "ĂN SẠCH SỐNG KHỎE",
    dateBadge: "Tháng 10",
    location: "Sảnh Dinh dưỡng & Căng tin Bệnh viện",
  },
  {
    id: "hoi-thao-phong-ngua-viem-loet-da-day-hp",
    title: "Chiến Dịch Truyền Thông: Đẩy Lùi Viêm Loét Dạ Dày & Vi Khuẩn HP",
    category: "public_health",
    categoryLabel: "Tiêu Hóa Dạ Dày",
    imageSrc: "/media/events/hoi-thao-phong-ngua-viem-loet-da-day-hp.jpg",
    imageAlt: "Hình ảnh mô phỏng dạ dày và vi khuẩn HP được kiểm soát bằng phác đồ chuẩn",
    description: "Tư vấn phác đồ tiệt trừ vi khuẩn Helicobacter pylori, chế độ ăn giảm acid và biện pháp ngăn ngừa loét tái phát.",
    tag: "DẠ DÀY AN TÂM",
    dateBadge: "Tháng 4",
    location: "Khoa Tiêu hóa & Gan mật",
  },
  {
    id: "chien-dich-truyen-thong-song-khoe-giam-muoi",
    title: "Chiến Dịch Quốc Gia: Giảm Muối Trong Bữa Ăn - Bảo Vệ Trái Tim",
    category: "public_health",
    categoryLabel: "Dinh Dưỡng Tim Mạch",
    imageSrc: "/media/events/chien-dich-truyen-thong-song-khoe-giam-muoi.jpg",
    imageAlt: "Người nội trợ lựa chọn gia vị thảo mộc tự nhiên thay thế lượng muối dư thừa",
    description: "Hướng dẫn thực đơn ít muối dưới 5g/ngày chuẩn WHO nhằm giảm nguy cơ đột quỵ và gánh nặng suy thận mạn tính.",
    tag: "ĂN LÀNH SỐNG KHỎE",
    dateBadge: "Tháng 3",
    location: "Hệ thống Màn hình Bệnh viện",
  },
  {
    id: "ngay-hoi-kham-sang-loc-benh-ly-cot-song",
    title: "Ngày Hội Tầm Soát: Thoát Vị Đĩa Đệm & Thoái Hóa Cột Sống",
    category: "public_health",
    categoryLabel: "Cột Sống Vững Vàng",
    imageSrc: "/media/events/ngay-hoi-kham-sang-loc-benh-ly-cot-song.jpg",
    imageAlt: "Mô hình đốt sống thắt lưng và đĩa đệm được bác sĩ phân tích nguyên nhân chèn ép thần kinh",
    description: "Khám chuyên sâu cột sống, tầm soát thoát vị đĩa đệm và hướng dẫn bài tập bơi lội, vật lý trị liệu giữ thẳng cột sống.",
    tag: "CỘT SỐNG VỮNG VÀNG",
    dateBadge: "Tháng 9",
    location: "Khoa Phẫu thuật Cột sống & Phục hồi Chức năng",
  },
  {
    id: "chien-dich-truyen-thong-su-dung-khang-sinh-co-trach-nhiem",
    title: "Tuần Lễ Toàn Cầu: Sử Dụng Kháng Sinh Có Trách Nhiệm - Chống Kháng Thuốc",
    category: "public_health",
    categoryLabel: "Y Tế Dự Phòng",
    imageSrc: "/media/events/chien-dich-truyen-thong-su-dung-khang-sinh-co-trach-nhiem.jpg",
    imageAlt: "Dụng cụ tiêm thuốc và bơm kim tiêm chuẩn vô trùng tại phòng tiêm chủng",
    description: "Cam kết không tự ý mua và sử dụng kháng sinh khi chưa có đơn bác sĩ, góp phần ngăn chặn thảm họa kháng thuốc toàn cầu.",
    tag: "BẢO VỆ KHÁNG SINH",
    dateBadge: "Tháng 11",
    location: "Toàn bộ Cơ sở Khám chữa bệnh",
  },

  // ==========================================
  // 6. Hoạt động nội bộ & Văn hóa bệnh viện
  // ==========================================
  {
    id: "hoi-thi-dieu-duong-gioi-thanh-lich",
    title: "Hội Thi 'Điều Dưỡng Giỏi - Tận Tâm - Thanh Lịch' Toàn Viện",
    category: "internal_life",
    categoryLabel: "Hội Thi Nghiệp Vụ",
    imageSrc: "/media/events/hoi-thi-dieu-duong-gioi-thanh-lich.jpg",
    imageAlt: "Nữ điều dưỡng tận tình lắng nghe và ghi nhận thông tin bệnh nhân",
    description: "Hội thi nâng cao kỹ năng giao tiếp ứng xử, quy trình chăm sóc chuẩn và nét đẹp thanh lịch của người điều dưỡng.",
    tag: "TẬN TÂM CHĂM SÓC",
    dateBadge: "12 tháng 5",
    location: "Hội trường Grand Hall",
  },
  {
    id: "ngay-hoi-the-thao-benh-vien",
    title: "Hội Thao Thường Niên Cán Bộ Nhân Viên Bệnh Viện HealthCare",
    category: "internal_life",
    categoryLabel: "Hội Thao Bệnh Viện",
    imageSrc: "/media/events/ngay-hoi-the-thao-benh-vien.jpg",
    imageAlt: "Cán bộ y tế tập luyện thể thao nâng cao sức bền thể lực",
    description: "Sân chơi thể thao gắn kết tình đồng nghiệp với các bộ môn bóng đá, bóng chuyền, cầu lông và chạy tiếp sức.",
    tag: "KHỎE ĐỂ CỐNG HIẾN",
    dateBadge: "Hàng năm",
    location: "Khu thể thao phức hợp & Nhà thi đấu",
  },
  {
    id: "gala-vinh-danh-blouse-trang-xuat-sac",
    title: "Đêm Gala Tri Ân & Vinh Danh Các Chiến Sĩ Áo Trắng Xuất Sắc",
    category: "internal_life",
    categoryLabel: "Gala Cuối Năm",
    imageSrc: "/media/events/gala-vinh-danh-blouse-trang-xuat-sac.jpg",
    imageAlt: "Toàn cảnh khuôn viên bệnh viện rực rỡ ánh đèn trong đêm tiệc vinh danh cuối năm",
    description: "Buổi tối ấm cúng tổng kết chặng đường phục vụ người bệnh và vinh danh những cá nhân, tập thể có đóng góp xuất sắc.",
    tag: "TỰ HÀO HEALTHCARE",
    dateBadge: "Tháng 12",
    location: "Khuôn viên ngoài trời & Hội trường Grand Hall",
  },
  {
    id: "hoi-thi-sang-kien-cai-tien-chat-luong-kizen",
    title: "Hội Thi Sáng Kiến Cải Tiến Chất Lượng Bệnh Viện Kaizen Thường Niên",
    category: "internal_life",
    categoryLabel: "Cải Tiến Chất Lượng",
    imageSrc: "/media/events/hoi-thi-sang-kien-cai-tien-chat-luong-kizen.jpg",
    imageAlt: "Góc phòng làm việc lâm sàng khoa học và hiện đại",
    description: "Biểu dương 30 sáng kiến rút ngắn thời gian chờ đợi khám và nâng cao chỉ số hài lòng của bệnh nhân và thân nhân.",
    tag: "ĐỔI MỚI LIÊN TỤC",
    dateBadge: "Tháng 11",
    location: "Phòng Họp Ban Giám Đốc",
  },
  {
    id: "hoi-thao-cham-soc-giam-nhe-noi-tru",
    title: "Khóa Huấn Luyện Nội Bộ: Kỹ Năng Giao Tiếp Y Khoa & Thấu Cảm",
    category: "internal_life",
    categoryLabel: "Văn Hóa Y Đức",
    imageSrc: "/media/events/hoi-thao-cham-soc-giam-nhe-noi-tru.jpg",
    imageAlt: "Nữ bác sĩ trao đổi, chia sẻ và đồng cảm với thân nhân người bệnh",
    description: "Đào tạo kỹ năng giao tiếp y khoa, nghệ thuật lắng nghe và giải thích tình trạng bệnh giúp xoa dịu tâm lý gia đình.",
    tag: "VĂN HÓA Y ĐỨC",
    dateBadge: "Hàng quý",
    location: "Trung tâm Đào tạo Kỹ năng Mềm",
  },
  {
    id: "ngay-hoi-gia-dinh-blouse-trang-gan-ket",
    title: "Ngày Hội Gia Đình Blouse Trắng: Gắn Kết Yêu Thương - Tiếp Lửa Y Đức",
    category: "internal_life",
    categoryLabel: "Đời Sống Cán Bộ",
    imageSrc: "/media/events/ngay-hoi-gia-dinh-blouse-trang-gan-ket.jpg",
    imageAlt: "Không gian dã ngoại ngoài trời xanh mát của ngày hội gia đình nhân viên bệnh viện",
    description: "Hoạt động dã ngoại gắn kết tình đồng nghiệp, tri ân hậu phương vững chắc giúp các y bác sĩ yên tâm cống hiến.",
    tag: "MÁI NHÀ HEALTHCARE",
    dateBadge: "Tháng 7",
    location: "Khuôn viên Công viên Bệnh viện",
  },
  {
    id: "le-vinh-danh-cong-trinh-nghien-cuu-y-khoa-xuat-sac",
    title: "Lễ Vinh Danh Công Trình Nghiên Cứu Y Khoa & Đề Tài Sáng Tạo Cấp Bộ",
    category: "internal_life",
    categoryLabel: "Nghiên Cứu Khoa Học",
    imageSrc: "/media/events/le-vinh-danh-cong-trinh-nghien-cuu-y-khoa-xuat-sac.jpg",
    imageAlt: "Toàn cảnh tòa nhà nghiên cứu y học hiện đại trong ngày vinh danh công trình khoa học",
    description: "Biểu dương 15 công trình nghiên cứu lâm sàng xuất sắc được công bố trên các tạp chí y khoa quốc tế uy tín.",
    tag: "TỰ HÀO NGHIÊN CỨU",
    dateBadge: "Tháng 12",
    location: "Hội trường Viện Nghiên cứu Y Sinh",
  },
] as const;

/**
 * Tra cứu thông tin hình ảnh sự kiện theo ID
 */
export function getEventVisual(id: string): EventVisual | undefined {
  return HOSPITAL_EVENTS_CATALOG.find((event) => event.id === id);
}

/**
 * Lọc danh sách sự kiện theo chuyên mục
 */
export function getEventsByCategory(category: EventCategory): EventVisual[] {
  return HOSPITAL_EVENTS_CATALOG.filter((event) => event.category === category);
}

/**
 * Lấy toàn bộ danh mục sự kiện bệnh viện
 */
export function getAllEvents(): readonly EventVisual[] {
  return HOSPITAL_EVENTS_CATALOG;
}
